/////////////////////
// COMMANDSET.INC //
///////////////////
//Rohan//
////////

//-------------------
CommandSet RohanSpellBookCommandSet
	1 = Command_SpellBookHeal
	2 = Command_SpellBookRallyingCall
	3 = Command_SpellBookRebuild
	
	4 = Command_SpellBookTomBombadil
	5 = Command_SpellBookHobbitAllies
	6 = Command_SpellBookLoneTower
	7 = Command_SpellBookArrowVolleyGood

	8 = Command_SpellBookCloudBreak
	9 = Command_SpellBookRohanAllies
	10 = Command_SpellBookDunedainAllies

	11 = Command_SpellBookArmyoftheDead
	12 = Command_SpellBookEarthquake
End

CommandSet RohanSpellStoreCommandSet
	1 = Command_PurchaseSpellHeal
	2 = Command_PurchaseSpellRallyingCallMP
	3 = Command_PurchaseSpellRebuild
	
	4 = Command_PurchaseSpellHobbitAllies
	5 = Command_PurchaseSpellArrowVolleyGood
	6 = Command_PurchaseSpellTomBombadil
	7 = Command_PurchaseSpellLoneTowerMen

	8 = Command_PurchaseSpellDunedainAllies
	9 = Command_PurchaseSpellCloudBreak
	10 = Command_PurchaseSpellRohanAllies

	11 = Command_PurchaseSpellArmyoftheDead
	12 = Command_PurchaseSpellEarthquake
End

///////////////////////////UNITS
CommandSet PeasantCommandSet
	1	= Command_Repair
	13	= Command_AttackMove
	14	= Command_Stop
End



CommandSet RohanTreeBeardCommandSet
	1	= Command_ToggleStance
	2	= Command_ToggleTreebeardRockThrow
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanTreeBeardRockCommandSet
	1	= Command_ToggleStance
	2	= Command_ToggleTreebeardRockThrow
	3	= Command_Bombard
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohanTreeBeardRockCommandSetStopBombard
	1	= Command_ToggleStance
	2	= Command_ToggleTreebeardRockThrow
	3	= Command_StopBombard
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanEntCommandSet
	1	= Command_ToggleStance
	2	= Command_ToggleEntRockThrow
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanEntRockCommandSet
	1	= Command_ToggleStance
	2	= Command_ToggleEntRockThrow
	3	= Command_Bombard
	13	= Command_AttackMove
	14	= Command_Stop
	16 	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanEntRockCommandSetStopBombard
	1	= Command_ToggleStance
	2	= Command_ToggleEntRockThrow
	3	= Command_StopBombard
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanEntCommandSetForOldForestRoad
	1	= Command_ToggleStance
	2	= Command_ToggleEntRockThrow
	3	= Command_Bombard
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanTheodenCommandSet
	1	= Command_ToggleStance
	2	= Command_TheodenToggleMounted
	3	= Command_SpecialAbilityTheodenLeadership
	4	= Command_SpecialAbilityKingsFavor
	5	= Command_SpecialAbilityTheodenGloriousCharge
	12 	= Command_CaptureBuilding
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet TheodenCavalryCommandSet
	1	= Command_ToggleStance
	2	= Command_SpecialAbilityRousingSpeech
	3	= Command_SpecialAbilityGrabPassenger
	4	= Command_TransportEvacuateTheoden
	12 	= Command_CaptureBuilding
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanPikeCommandSet
	1 	= Command_ToggleStance		
	2	= Command_RohanPorcupineFormation
	3 	= Command_PurchaseUpgradeGondorForgedBlades
	4 	= Command_PurchaseUpgradeGondorHeavyArmor
	5 	= Command_PurchaseUpgradeGondorBasicTraining
	12 	= Command_CaptureBuilding
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End




CommandSet RohanRohirrimCommandSet
	1	= Command_ToggleStance 	
	2	= Command_ToggleRohirrimWeapon 
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanArcherCommandSet
	1	= Command_ToggleStance
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanElvenWarriorCommandSet
	1	= Command_ToggleStance
	2	= Command_ToggleElvenWarriorWeapon
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

//--------------Rohan Hordes
//Note we need to split this up via commandset upgrades so all the appropriate buttons can be seen.
CommandSet RohirrimHordeCommandSet	
	1 = Command_ToggleStance
	2 = Command_ToggleRohirrimWeapon
	3 = Command_PurchaseUpgradeRohanForgedBladesForRohirrim	
	4 = Command_PurchaseUpgradeRohanHeavyArmorForRohirrim
	5 = Command_PurchaseUpgradeRohanBasicTraining
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohirrimHordeBowCommandSet	
	1 = Command_ToggleStance
	2 = Command_ToggleRohirrimWeapon
	3 = Command_PurchaseUpgradeRohanFireArrows
	4 = Command_PurchaseUpgradeRohanHeavyArmorForRohirrim
	5 = Command_PurchaseUpgradeRohanBasicTraining
	12 = Command_CaptureBuilding
	13 = Command_AttackMove
	14 = Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohirrimHordeCommandSet_Summoned
	1	= Command_ToggleStance
	12 	= Command_CaptureBuilding
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohirrimArcherHordeCommandSet
	1 	= Command_ToggleStance
	2 	= Command_ToggleFormationRohirrimArcher
	3 	= Command_PurchaseUpgradeRohanHeavyArmorForRohirrimArchers
	4 	= Command_PurchaseUpgradeRohanFireArrows
	5 	= Command_PurchaseUpgradeRohanBasicTraining
	12 	= Command_CaptureBuilding
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanArcherHordeCommandSet
	1 	= Command_ToggleStance
	2 	= Command_ToggleFormationRohanArcherHorde
	3 	= Command_PurchaseUpgradeRohanHeavyArmorForArchers
	4 	= Command_PurchaseUpgradeRohanFireArrows
	5 	= Command_PurchaseUpgradeRohanBasicTraining
	12 	= Command_CaptureBuilding
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanPeasantHordeCommandSet
	1	= Command_ToggleStance	
	2 	= Command_Repair
	3 	= Command_PurchaseUpgradeRohanForgedBladesForPeasants
	4 	= Command_PurchaseUpgradeRohanHeavyArmorForPeasants
	5 	= Command_PurchaseUpgradeRohanBasicTraining
	12 	= Command_CaptureBuilding
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanElvenWarriorHordeCommandSet
	1 	= Command_ToggleStance
	2 	= Command_ToggleElvenWarriorWeapon
	3 	= Command_PurchaseUpgradeRohanForgedBladesForElves
	4 	= Command_PurchaseUpgradeRohanHeavyArmorForElves
	5 	= Command_PurchaseUpgradeRohanFireArrows
	6 	= Command_PurchaseUpgradeRohanBasicTraining
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanElvenWarriorHordeCommandSet_Summoned
	1 	= Command_ToggleStance
	2 	= Command_ToggleElvenWarriorWeapon
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanOathbreakerHordeCommandSet
	1	= Command_ToggleStance
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanOathbreakerHordeSmallCommandSet
	1	= Command_ToggleStance
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End

CommandSet RohanRoyalGuardHordeCommandSet
	1	= Command_ToggleStance	
	13	= Command_AttackMove
	14	= Command_Stop
	16  	= Command_SetStanceBattle
	17  	= Command_SetStanceAggressive
	18  	= Command_SetStanceHoldGround
End



CommandSet RohanFarmCommandSet
	1	= Command_ConstructRohanPeasantHorde
	6	= Command_Sell
End


CommandSet RohanGenericEntCommandSet
	 1 = Command_ToggleStance
	13 = Command_AttackMove	
	14 = Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End



//------------------------------------//
// ROHAN UNIT PRODUCTION COMMAND SETS //
//------------------------------------//
CommandSet RohanStablesCommandSet
	1 = Command_ConstructRohanRohirrimHorde
	2 = Command_ConstructRohanRohirrimArcherHorde
	3 = Command_PurchaseTechnologyRohanHorseShield
	6 = Command_Sell
End

CommandSet RohanArcherRangeCommandSet
	1 = Command_ConstructRohanArcherHorde
	2 = Command_ConstructRohanElvenWarriorHorde
	3 = Command_PurchaseTechnologyRohanFireArrows
	6 = Command_Sell
End


CommandSet RohanArmoryCommandSet
	1 = Command_PurchaseTechnologyRohanBasicTraining
	2 = Command_PurchaseTechnologyRohanHeavyArmor
	3 = Command_PurchaseTechnologyRohanForgedBlades
	6 = Command_Sell
End



CommandSet RohanFrodoCommandSet
	1	= Command_ToggleStance  
	2	= Command_ToggleFrodoWeapon
	3	= Command_SpecialAbilityElfCloak
	4	= Command_SpecialAbilityPhialOfGaladriel
	12	= Command_CaptureBuilding
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohanSamWithFrodoPowersCommandSet
	1	= Command_ToggleStance
	2  	= Command_ToggleFrodoWeapon
	3  	= Command_SpecialAbilityElfCloakSam
	4  	= Command_SpecialAbilityPhialOfGaladrielSam
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohanPippinCommandSet
	1	= Command_ToggleStance
	2	= Command_ToggleHobbitRockThrow
	3	= Command_SpecialAbilityElfCloak
	12	= Command_CaptureBuilding
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohanSamCommandSet
	1	= Command_ToggleStance
	2	= Command_ToggleHobbitRockThrow
	3	= Command_SpecialAbilityElfCloakSam
	12 = Command_CaptureBuilding	
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohanEomerCommandSet
	1	= Command_ToggleStance
	2	= Command_MountHorseEomer 
	3	= Command_RohanEomerHorseLordLeadership
	4	= Command_RohanEomerOutlawLeadership
	5	= Command_RohanEomerSpear
  	12	= Command_CaptureBuilding
  	13	= Command_AttackMove
  	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohanEowynCommandSet
	1	= Command_ToggleStance
	2 	= Command_EowynSmite  
	3 	= Command_MountHorseEowyn
	4 	= Command_Disguise
	5 	= Command_EowynShieldMaiden
	12 	= Command_CaptureBuilding
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohanGamlingCommandSet
	1	= Command_ToggleStance
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End



CommandSet RohanBaseDefenceFoundationCommandSet
	1 = Command_ConstructRohanSentryTower
End

CommandSet RohanEconomyPlotCommandSet
  1  = Command_UnpackExplicitRohanFarm
  2  = Command_ConstructEntMoot
End

CommandSet RohanFoundationCommandSet
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanArcherRange
  3  = Command_ConstructRohanStable
  4  = Command_ConstructRohanArmory
End

CommandSet RohanFoundationCommandSetUpgradedEntMoot
  1  = Command_ConstructRohanFarm
  2  = Command_ConstructRohanArcherRange
  3  = Command_ConstructRohanStable
  4  = Command_ConstructRohanArmory
  5  = Command_ConstructEntMoot
End


CommandSet RohanWallFoundationCommandSet
  1  = Command_ConstructRohanWall
End



CommandSet RohanCastleWallCommandSet
	1 = Command_UpgradeRohanWallBanner
	2 = Command_UpgradeRohanOpenGarrison
	3 = Command_UpgradeRohanPosternGate
End


CommandSet RohanCastleBaseKeepCommandSet
	1	= Command_GenericReviveSlot1
	2	= Command_GenericReviveSlot2
	3	= Command_GenericReviveSlot3
	4	= Command_GenericReviveSlot4
	5	= Command_GenericReviveSlot5
	6	= Command_GenericReviveSlot6
	7	= Command_GenericReviveSlot7
	9	= Command_StartCitadelSelfRepair
End


CommandSet RohanHobbitCommandSet
	1	= Command_ToggleStance	
	2	= Command_ToggleHobbitRockThrow
	13	= Command_AttackMove
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End



CommandSet RohanHobbitHordeCommandSet
	1	= Command_ToggleStance
	2	= Command_ToggleHobbitRockThrow
	12	= Command_CaptureBuilding
	13	= Command_AttackMove	
	14	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End

CommandSet RohanHobbitHordeCommandSet_Summoned	
	1	= Command_ToggleStance
	2	= Command_ToggleHobbitRockThrow
	12  = Command_CaptureBuilding
	13 	= Command_AttackMove
	14 	= Command_Stop
	16  = Command_SetStanceBattle
	17  = Command_SetStanceAggressive
	18  = Command_SetStanceHoldGround
End
