////////////////
// ARMOR.INC //
//////////////
//Dwarves//
//////////



;//////////////////////DWARVEN ARMORS///////////////////////////////////////////
Armor DwarvenAxeThrowerArmor
  Armor = DEFAULT         	 80%   	; 100%	originally 100%
  Armor = SLASH           	125%   	; 100%	originally 100%
  Armor = PIERCE          	 70%   	;  50% 	originally 100%  RotWK originally 90%
  Armor = SPECIALIST      	 90%   	;  50%	originally 100%
  Armor = CRUSH           	200%   	; 200%
  Armor = SIEGE           	100%   	;
  Armor = FLAME           	100%   	;  30%
  Armor = FROST           	100%    ;
  Armor = MAGIC           	100%   	;
  Armor = HERO            	200%   	;
  Armor = HERO_RANGED     	200%   	;
  Armor = CAVALRY	  	175%	; originally 200%  
  Armor = STRUCTURAL	  	 30%	; originally 100%		
  FlankedPenalty 	       = 50%   
End

;------------------------------------------------------------------------------
Armor DwarvenAxeThrowerHeavyArmor
  Armor = DEFAULT         	 35% 	;
  Armor = SLASH          	 45% 	; originally 50%
  Armor = PIERCE          	 35% 	; originally 50%	RotWK originally 45%
  Armor = SPECIALIST      	 45% 	; originally 50%
  Armor = CRUSH           	100% 	;
  Armor = SIEGE           	 50% 	;
  Armor = FLAME           	 50% 	;
  Armor = FROST           	 50%   	;
  Armor = MAGIC           	 50% 	;
  Armor = HERO            	100% 	;
  Armor = HERO_RANGED    	100% 	;
  Armor = CAVALRY	  	 90%	; originally 100%
  Armor = STRUCTURAL	  	 20%	
  FlankedPenalty 	       = 50%  
End

;------------------------------------------------------------------------------
Armor DwarvenGuardianArmor
  Armor = DEFAULT         	 60%	; originally 100%
  Armor = SLASH           	 60% 	; originally 100% 
  Armor = PIERCE          	 50% 	; originally 150%	RotWK originally 60%
  Armor = SPECIALIST      	 20% 	; originally  40%
  Armor = CRUSH           	110% 	; originally 100%
  Armor = SIEGE           	100%	;	
  Armor = FLAME           	100%	;
  Armor = FROST           	100%   	;
  Armor = MAGIC           	100% 	;
  Armor = HERO            	200%	;	
  Armor = CAVALRY	  	150%	;
  Armor = HERO_RANGED     	200%	;
  Armor = STRUCTURAL	  	 45%	; originally 100%	
  FlankedPenalty 	       = 50%
End

;------------------------------------------------------------------------------
Armor DwarvenGuardianHeavyArmor
  Armor = DEFAULT         	 30%   	;  40% 		originally 50%
  Armor = SLASH           	 30%   	;  40%		originally 50%
  Armor = PIERCE          	 25%   	;  20%		originally 50%	RotWK originally 30%
  Armor = SPECIALIST      	 10%   	; 		originally 20%
  Armor = CRUSH           	 55%   	;  		originally 50%
  Armor = SIEGE           	 50%   	; 100%
  Armor = FLAME           	 50%   	;   0%
  Armor = FROST           50%   ;
  Armor = MAGIC           	 50%   	; 100%
  Armor = HERO            	100%   	;  50%
  Armor = HERO_RANGED     	100%   	;  50%  
  Armor = CAVALRY	  	 85% 	; 		originally 75%
  Armor = STRUCTURAL	  	 15%	;		originally 20%
  FlankedPenalty 	       = 50%      
End

;------------------------------------------------------------------------------
Armor DwarvenDemolisherArmor
  Armor = DEFAULT         	 40%   	; 100%	originally 50%
  Armor = SLASH           	 90%   	; 100%	originally 100%
  Armor = PIERCE          	 25%   	;  50%
  Armor = SPECIALIST      	 40%   	;  50%	originally 100%
  Armor = CRUSH           	  1%   	; 200%
  Armor = SIEGE           	100%   	;
  Armor = FLAME           	100%   	;  30%
  Armor = FROST           125%   ;
  Armor = MAGIC           	100%   	;
  Armor = HERO            	200%   	; 
  Armor = HERO_RANGED     	100%   	; 
  Armor = STRUCTURAL	  	 25%	;
  Armor = CAVALRY	  	 50%    ;
End

;------------------------------------------------------------------------------
Armor DwarvenDemolisherHeavyArmor
  Armor = DEFAULT         	 20%   	;  40%	originally 25%
  Armor = SLASH           	 45%   	;  40%	originally 50%
  Armor = PIERCE          	 10%   	;  20%	originally 15%
  Armor = SPECIALIST      	 40%   	;	originally 50%
  Armor = CRUSH           	  1%   	;  50%
  Armor = SIEGE           	 75%   	; 100%
  Armor = FLAME           	 50%   	;   0%
  Armor = FROST           75%   ;
  Armor = MAGIC           	 50%   	; 100%
  Armor = HERO            	 50%   	;  50%
  Armor = HERO_RANGED     	 50%   	;  50%   
  Armor = STRUCTURAL	  	 10%	;
  Armor = CAVALRY	  	 25% 	;	originally 50%
End

;------------------------------------------------------------------------------
Armor DwarvenPikemenArmor
  Armor = DEFAULT        	 75%   	; 100%	originally 100%
  Armor = SLASH          	130%   	;	originally 140%
  Armor = PIERCE         	 90%   	;  50% 	originally 125%		RotWK originally 110%
  Armor = SPECIALIST     	 80%   	;	originally 100%
  Armor = CRUSH          	 10%   	;  50%
  Armor = SIEGE          	100%   	;
  Armor = FLAME          	100%   	;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC          	100%   	;
  Armor = HERO           	200%   	;
  Armor = HERO_RANGED  	 	200%   	;
  Armor = STRUCTURAL	 	 50%   	;	originally 100%
  Armor = CAVALRY	  	 20%
  FlankedPenalty 	      = 100%         
End

;------------------------------------------------------------------------------
Armor DwarvenPikemenHeavyArmor
  Armor = DEFAULT          	 35% 	; 40%	originally 50%
  Armor = SLASH            	 80% 	; 	Originally 100%
  Armor = PIERCE           	 45% 	; 20% 	originally 65%		RotWK originally 70%
  Armor = SPECIALIST       	 40% 	;	originally 50%
  Armor = CRUSH            	  5%  	; 40%
  Armor = SIEGE                  50% 	; 100%
  Armor = FLAME            	 50% 	; 0%
  Armor = FROST          	 50%   ;
  Armor = MAGIC                  50% 	; 100%
  Armor = HERO                  100% 	; 50%
  Armor = HERO_RANGED           100% 	; 50%  
  Armor = STRUCTURAL	         20%	;	
  Armor = CAVALRY	         10%	;	
  FlankedPenalty 	      = 100%     
End

;//------------------------------------------------------------------------------
Armor BattleWagonArmor
  Armor = DEFAULT        	 85%    ; 	originally 100%
  Armor = SLASH          	 30%    ; 	originally 100%, Expansion was 80% originally  RotWK originally 50%
  Armor = CRUSH          	  1% 	;
  Armor = PIERCE         	 20%	;	originally 50%, Expansion was 60% originally  RotWK originally 30%
  Armor = SIEGE          	100%    ; 
  Armor = STRUCTURAL	 	 85%	; 	originally 100%
  Armor = HERO		 	200%    ; 
  Armor = MAGIC		 	100%    ; 
  Armor = HERO_RANGED    	200%	; 
  Armor = FLAME          	 50%	; 
  Armor = FROST          	 50%   ;
  Armor = SPECIALIST     	200%    ; 	originally 200%
  Armor = CAVALRY	 	125%	;	originally 100%
End

;//------------------------------------------------------------------------------
Armor BattleWagonArmorHeavy
  Armor = DEFAULT             	 40% 	;	
  Armor = SLASH               	 15% 	;	originally 40% 	RotWK originally 25%
  Armor = CRUSH            	  1% 	;	
  Armor = PIERCE         	 10%	;   	originally 25%	RotWK originally 15%
  Armor = SIEGE             	 50% 	;	
  Armor = STRUCTURAL		 30%	; 	originally 20%
  Armor = HERO			100% 	;	
  Armor = MAGIC			 50% 	;	
  Armor = HERO_RANGED   	100%  	;	
  Armor = FLAME         	 25%  	;	
  Armor = FROST          	 50%   ;
  Armor = SPECIALIST        	 100%	;	originally 100%
  Armor = CAVALRY		 80%	;	originally 50%
End



;---------------------------------------------------------------------------------------------
Armor DwarvenWallArmor           	; MOTW generic wall armor 
  Armor = DEFAULT       	  5%    ; this sets the level for all nonspecified damage types
  Armor = SIEGE          	 85%    ; siege damage						Originally 200%
  Armor = PIERCE        	  1%    ; archer damage
  Armor = FLAME         	  1%    ;
  Armor = STRUCTURAL		 25%	; structural damage - Grond inflicts this kind of damage
  Armor = LOGICAL_FIRE		  0%	; Fire
End
