////////////////////////////
// ATTRIBUTEMODIFIER.INC //
//////////////////////////
//Dwarves//
//////////

ModifierList DwarvenMineShaftBonusLevel2
	Category		= SPELL
	Modifier	= PRODUCTION DWARVEN_MINE_LVL2_PRODUCTION			
	Modifier	= COMMAND_POINT_BONUS 25	
	Modifier	= HEALTH DWARVEN_MINE_LVL2_HP_ADD
	Duration		= 0
End

ModifierList DwarvenMineShaftBonusLevel3
	Category		= SPELL
	Modifier	= PRODUCTION DWARVEN_MINE_LVL3_PRODUCTION			
	Modifier	= COMMAND_POINT_BONUS 25	
	Modifier	= HEALTH DWARVEN_MINE_LVL3_HP_ADD
	Duration		= 0
End
