; ####################################################
; "Battle for Middle Earth II - Special Extended Edition - Director's Cut"
; ####################################################

; Upgrade.INC for S.E.E....
; ------------------------------------------------------------------------------ 
; NOTE: These codes are ported from Sûlherokkh's coding in Beta 4.7!

//Cheat mode for testing purposes!
Upgrade Upgrade_Fast_Gameplay_SEE 
  Type = OBJECT
End

Upgrade Upgrade_ObjectUnderAIControl //_SEE  ;only available for the AI
  Type = OBJECT
End

Upgrade Upgrade_ReallyDamaged_SEE
  Type = OBJECT
  BuildTime = 0.0
  BuildCost = 0
End 

Upgrade Upgrade_FortressHasBeenEntered_SEE
  Type = OBJECT
  BuildTime = 0.0
  BuildCost = 0
End
