////////////////
// VOICE.INC //
//////////////
//Missions//
///////////

;=============================Expansion Mission Voice============================================

;-----------------------------Mission 1 Foundation-----------------------------------------

AudioEvent MAFound_AngmarOff01
  Sounds = MAFound_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff02
  Sounds = MAFound_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff03
  Sounds = MAFound_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff04
  Sounds = MAFound_AnOf004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff05
  Sounds = MAFound_AnOf005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff06
  Sounds = MAFound_AnOf006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff07
  Sounds = MAFound_AnOf007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff08
  Sounds = MAFound_AnOf008
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff09
  Sounds = MAFound_AnOf009
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff10
  Sounds = MAFound_AnOf010
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff11
  Sounds = MAFound_AnOf011
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff12
  Sounds = MAFound_AnOf012
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff13
  Sounds = MAFound_AnOf013
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff14
  Sounds = MAFound_AnOf014
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff15
  Sounds = MAFound_AnOf015
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff16
  Sounds = MAFound_AnOf016
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff17
  Sounds = MAFound_AnOf017
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_AngmarOff18
  Sounds = MAFound_AnOf018
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MAFound_Witchking01
  Sounds = MAFound_Wtkg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking02
  Sounds = MAFound_Wtkg002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking03
  Sounds = MAFound_Wtkg003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking04
  Sounds = MAFound_Wtkg004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking05
  Sounds = MAFound_Wtkg005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking06
  Sounds = MAFound_Wtkg006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking07
  Sounds = MAFound_Wtkg007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking08
  Sounds = MAFound_Wtkg008
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking09
  Sounds = MAFound_Wtkg009
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Witchking10
  Sounds = MAFound_Wtkg010
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Rogash01
  Sounds = MAFound_Roga001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Rogash02
  Sounds = MAFound_Roga002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAFound_Rogash03
  Sounds = MAFound_Roga003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


;-----------------------------Mission 2 Gundabad--------------------------------------------
AudioEvent MAGunda_AngmarOff01
  Sounds = MAGunda_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff02
  Sounds = MAGunda_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff03
  Sounds = MAGunda_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff04
  Sounds = MAGunda_AnOf004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff05
  Sounds = MAGunda_AnOf005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff06
  Sounds = MAGunda_AnOf006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff07
  Sounds = MAGunda_AnOf007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff08
  Sounds = MAGunda_AnOf008
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff09
  Sounds = MAGunda_AnOf009
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff10
  Sounds = MAGunda_AnOf010
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff11
  Sounds = MAGunda_AnOf011
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff12
  Sounds = MAGunda_AnOf012
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_AngmarOff13
  Sounds = MAGunda_AnOf013
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MAGunda_Ranger01
  Sounds = MAGunda_Rngr001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Ranger02
  Sounds = MAGunda_Rngr002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Ranger03
  Sounds = MAGunda_Rngr003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Ranger04
  Sounds = MAGunda_Rngr004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Ranger05
  Sounds = MAGunda_Rngr005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Ranger06
  Sounds = MAGunda_Rngr006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Rogash01
  Sounds = MAGunda_Roga001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Rogash02
  Sounds = MAGunda_Roga002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Rogash03
  Sounds = MAGunda_Roga003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Rogash04
  Sounds = MAGunda_Roga004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Rogash05
  Sounds = MAGunda_Roga005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Goblin01
  Sounds = MAGunda_Gobl001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Goblin02
  Sounds = MAGunda_Gobl002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Goblin03
  Sounds = MAGunda_Gobl003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Goblin04
  Sounds = MAGunda_Gobl004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Orcs02
  Sounds = MAGunda_Orcs002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Orcs03
  Sounds = MAGunda_Orcs003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Orcs04
  Sounds = MAGunda_Orcs004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Orcs01
  Sounds = MAGunda_Orcs001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MAGunda_Orcs05
  Sounds = MAGunda_Orcs005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAGunda_Orcs06
  Sounds = MAGunda_Orcs006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MAGunda_Orcs07
  Sounds = MAGunda_Orcs007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End



;-----------------------------Mission 3 Rhudaur----------------------------------------------

AudioEvent MARhuda_AngmarOff01
  Sounds = MARhuda_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_AngmarOff02
  Sounds = MARhuda_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_AngmarOff03
  Sounds = MARhuda_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_AngmarOff04
  Sounds = MARhuda_AnOf004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_AngmarOff05
  Sounds = MARhuda_AnOf005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_AngmarOff06
  Sounds = MARhuda_AnOf006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_AngmarOff07
  Sounds = MARhuda_AnOf007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_AngmarOff08
  Sounds = MARhuda_AnOf008
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MARhuda_Argeleb01
  Sounds = MARhuda_Argl001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_Hillman01
  Sounds = MARhuda_Hillm001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_Hillman02
  Sounds = MARhuda_Hillm002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MARhuda_Witchking01
  Sounds = MARhuda_Wtkg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


;-----------------------------Mission 4 Amon Sul------------------------------------------------
AudioEvent MAAmonS_AngmarOff01
  Sounds = MAAmonS_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff02
  Sounds = MAAmonS_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff03
  Sounds = MAAmonS_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff04
  Sounds = MAAmonS_AnOf004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff05
  Sounds = MAAmonS_AnOf005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff06
  Sounds = MAAmonS_AnOf006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff07
  Sounds = MAAmonS_AnOf007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff08
  Sounds = MAAmonS_AnOf008
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff09
  Sounds = MAAmonS_AnOf009
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff10
  Sounds = MAAmonS_AnOf010
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff11
  Sounds = MAAmonS_AnOf011
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff12
  Sounds = MAAmonS_AnOf012
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff13
  Sounds = MAAmonS_AnOf013
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff14
  Sounds = MAAmonS_AnOf014
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff15
  Sounds = MAAmonS_AnOf015
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff16
  Sounds = MAAmonS_AnOf016
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff17
  Sounds = MAAmonS_AnOf017
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_AngmarOff18
  Sounds = MAAmonS_AnOf018
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End



AudioEvent MAAmonS_Hwaldar01
  Sounds = MAAmonS_Hwal001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_Hwaldar02
  Sounds = KUHwald_voigara
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_Morgramir01
  Sounds = MAAmonS_Morg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_Morgramir02
  Sounds = MAAmonS_Morg002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MAAmonS_Witchking01
  Sounds = MAAmonS_Wtkg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_Witchking02
  Sounds = MAAmonS_Wtkg002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_Witchking03
  Sounds = MAAmonS_Wtkg003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAAmonS_Witchking04
  Sounds = MAAmonS_Wtkg004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

;-----------------------------Mission 5 Dark Lords Eye--------------------------------------------

AudioEvent MADLEye_AngmarOff01
  Sounds = MADLEye_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_AngmarOff02
  Sounds = MADLEye_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_AngmarOff03
  Sounds = MADLEye_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

;AudioEvent MADLEye_AngmarOff04
;  Sounds = MADLEye_AnOf004
;  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
;  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
;  VolumeSliderMultiplier = Slider:Voice Multiplier:70
;  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
;  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
;  Type = world everyone voice
;  SubmixSlider = voice
;  Limit = 1
;End

AudioEvent MADLEye_AngmarOff05
  Sounds = MADLEye_AnOf005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_AngmarOff06
  Sounds = MADLEye_AnOf006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_AngmarOff07
  Sounds = MADLEye_AnOf007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_AngmarOff08
  Sounds = MADLEye_AnOf008
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_AngmarOff09
  Sounds = MADLEye_AnOf009
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADLEye_Morgramir01
  Sounds = MADLEye_Morg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Morgramir02
  Sounds = MADLEye_Morg002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Morgramir03
  Sounds = MADLEye_Morg003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Morgramir04
  Sounds = MADLEye_Morg004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Morgramir05
  Sounds = MADLEye_Morg005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Morgramir06
  Sounds = MADLEye_Morg006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End



AudioEvent MADLEye_ArnorCaptain01
  Sounds = MADLEye_ArnC001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_ArnorCaptain02
  Sounds = MADLEye_ArnC002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_ArnorSoldier01
  Sounds = MADLEye_ArnS001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_ArnorSoldier02
  Sounds = MADLEye_ArnS002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Ranger01
  Sounds = MADLEye_Rngr001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Arveleg01
  Sounds = MADLEye_Arvl001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Arveleg02
  Sounds = MADLEye_Arvl002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADLEye_Arveleg03
  Sounds = MADLEye_Arvl003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

;-----------------------------Mission 6 Barrow Downs-----------------------------------------
AudioEvent MABarDo_AngmarOff01
  Sounds = MABarDo_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff02
  Sounds = MABarDo_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff03
  Sounds = MABarDo_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff04
  Sounds = MABarDo_AnOf004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff05
  Sounds = MABarDo_AnOf005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff06
  Sounds = MABarDo_AnOf006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff07
  Sounds = MABarDo_AnOf007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff08
  Sounds = MABarDo_AnOf008
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff09
  Sounds = MABarDo_AnOf009
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff10
  Sounds = MABarDo_AnOf010
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff11
  Sounds = MABarDo_AnOf011
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff12
  Sounds = MABarDo_AnOf012
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff13
  Sounds = MABarDo_AnOf013
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff14
  Sounds = MABarDo_AnOf014
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MABarDo_AngmarOff15
  Sounds = MABarDo_AnOf015
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MABarDo_Witchking01
  Sounds = MABarDo_Wtkg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


;-----------------------------Mission 7 Carn Dum---------------------------------------------

AudioEvent MACarnD_AngmarOff01
  Sounds = MACarnD_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff02
  Sounds = MACarnD_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff03
  Sounds = MACarnD_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff04
  Sounds = MACarnD_AnOf004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff05
  Sounds = MACarnD_AnOf005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff06
  Sounds = MACarnD_AnOf006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff07
  Sounds = MACarnD_AnOf007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff08
  Sounds = MACarnD_AnOf008
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff09
  Sounds = MACarnD_AnOf009
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff10
  Sounds = MACarnD_AnOf010
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff11
  Sounds = MACarnD_AnOf011
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff12
  Sounds = MACarnD_AnOf012
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff13
  Sounds = MACarnD_AnOf013
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff14
  Sounds = MACarnD_AnOf014
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff15
  Sounds = MACarnD_AnOf015
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff16
  Sounds = MACarnD_AnOf016
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff17
  Sounds = MACarnD_AnOf017
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff18
  Sounds = MACarnD_AnOf018
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff19
  Sounds = MACarnD_AnOf019
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff20
  Sounds = MACarnD_AnOf020
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_AngmarOff21
  Sounds = MACarnD_AnOf021
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MACarnD_ElfCaptain01
  Sounds = MACarnD_ElfC001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_ElfCaptain02
  Sounds = MACarnD_ElfC002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MACarnD_Glorfindel01
  Sounds = MACarnD_Glor001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_Glorfindel02
  Sounds = MACarnD_Glor002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MACarnD_Rogash01
  Sounds = MACarnD_Roga001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

;-----------------------------Mission 8 Wights----------------------------------------------

AudioEvent MAWight_AngmarOff01
  Sounds = MAWight_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff02
  Sounds = MAWight_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff03
  Sounds = MAWight_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff04
  Sounds = MAWight_AnOf004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff05
  Sounds = MAWight_AnOf005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff06
  Sounds = MAWight_AnOf006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff07
  Sounds = MAWight_AnOf007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff08
  Sounds = MAWight_AnOf008 MAWight_AnOf009 		;MAWight_AnOf010
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff11
  Sounds = MAWight_AnOf011
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff12
  Sounds = MAWight_AnOf012 MAWight_AnOf013 MAWight_AnOf014
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff15
  Sounds = MAWight_AnOf015
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_AngmarOff16
  Sounds = MAWight_AnOf016
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MAWight_ArnorCaptain01
  Sounds = MAWight_ArnC001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_ArnorCaptain02
  Sounds = MAWight_ArnC002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_ArnorCaptain03
  Sounds = MAWight_ArnC003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MAWight_Carthaen01
  Sounds = MAWight_Cart001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_Carthaen02
  Sounds = MAWight_Cart002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_Carthaen03
  Sounds = MAWight_Cart003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_Carthaen04
  Sounds = MAWight_Cart004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_Morgramir01
  Sounds = MAWight_Morg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_Morgramir02
  Sounds = MAWight_Morg002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_Morgramir03
  Sounds = MAWight_Morg003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAWight_Morgramir04
  Sounds = MAWight_Morg004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End



;-----------------------------Mission 9 Fornost-----------------------------------------------


AudioEvent MAForno_AngmarOff01
  Sounds = MAForno_AnOf001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_AngmarOff02
  Sounds = MAForno_AnOf002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_AngmarOff03
  Sounds = MAForno_AnOf003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MAForno_ArnorCaptain01
  Sounds = MAForno_ArnC001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_ArnorCaptain02
  Sounds = MAForno_ArnC002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_ArnorCaptain03
  Sounds = MAForno_ArnC003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_Arvedui01
  Sounds = MAForno_Arvd001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_Arvedui02
  Sounds = MAForno_Arvd002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_Arvedui03
  Sounds = MAForno_Arvd003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_ElfCaptain01
  Sounds = MAForno_ElfC001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_ElfCaptain02
  Sounds = MAForno_ElfC002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_ElfCaptain03
  Sounds = MAForno_ElfC003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End



AudioEvent MAForno_Witchking01
  Sounds = MAForno_Wtkg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_Witchking02
  Sounds = MAForno_Wtkg002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_Witchking03
  Sounds = MAForno_Wtkg003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_Witchking04
  Sounds = MAForno_Wtkg004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MAForno_Witchking05
  Sounds = MAForno_Wtkg005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

;-----------------------------Mission 10 Desturction------------------------------------------

AudioEvent MADestr_Earnur01
  Sounds = MADestr_Earn001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADestr_Earnur02
  Sounds = MADestr_Earn002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADestr_Earnur03
  Sounds = MADestr_Earn003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADestr_Earnur04
  Sounds = MADestr_Earn004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADestr_Earnur05
  Sounds = MADestr_Earn005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADestr_Earnur06
  Sounds = MADestr_Earn006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

AudioEvent MADestr_Glorfindel01
  Sounds = MADestr_Glor001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Glorfindel02
  Sounds = MADestr_Glor002
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Glorfindel03
  Sounds = MADestr_Glor003
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Glorfindel04
  Sounds = MADestr_Glor004
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Glorfindel05
  Sounds = MADestr_Glor005
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Glorfindel06
  Sounds = MADestr_Glor006
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Glorfindel07
  Sounds = MADestr_Glor007
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Morgramir01
  Sounds = MADestr_Morg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Rogash01
  Sounds = MADestr_Roga001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Wisperer01
  Sounds = MADestr_Wisp001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End


AudioEvent MADestr_Witchking01
  Sounds = MADestr_Wtkg001
  Volume = #ADD( MISSION_DIALOG_VOLUME_REDUCED 0 )				;pickup session 1
  MinVolume = #ADD( MISSION_DIALOG_MINVOLUME_REDUCED 0 )		;pickup session 1
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Type = world everyone voice
  SubmixSlider = voice
  Limit = 1
End

;---------------------------------Witch-king Victory/defeat lines-------------------------------------------
