////////////////
// ARMOR.INC //
//////////////
//Gondor//
/////////



;//////////////////////MEN OF THE WEST ARMORS///////////////////////////////////////////
;------------------------------------------------------------------------------

Armor SoldierArmor
  Armor = DEFAULT         	 85%   	; 100%	originally 100%
  Armor = SLASH           	 85%   	; 100%	originally 100%
  Armor = PIERCE          	 70%   	;  50% 	originally 150%		RotWK originally 85%
  Armor = SPECIALIST      	 25%   	;  50%	originally 40%
  Armor = CRUSH           	125%   	; 200%
  Armor = CAVALRY	  	175%   	;	originally 150%
  Armor = SIEGE           	100%   	;
  Armor = FLAME           	100%   	;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%  	;
  Armor = HERO            	200%   	;
  Armor = HERO_RANGED     	200%   	; 
  Armor = STRUCTURAL	  	 50%	;	originally 100%
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------
Armor SoldierHeavyArmor
  Armor = DEFAULT             	40% 	;  40%	originally 50%
  Armor = SLASH               	40% 	;  40%	originally 50%
  Armor = PIERCE              	35% 	;  20% 	originally 75%		RotWK originally 40
  Armor = SPECIALIST          	10% 	;	originally 20%
  Armor = CAVALRY	       110% 	;	originally 75%
  Armor = CRUSH              	65% 	;  	originally 50%
  Armor = SIEGE               	50% 	; 100%
  Armor = FLAME               	50% 	;   0%
  Armor = FROST          	50%   ;
  Armor = MAGIC               	50% 	; 100%
  Armor = HERO                 100% 	;  50%
  Armor = HERO_RANGED          100% 	;  50%  
  Armor = STRUCTURAL	  	20%	;	
  FlankedPenalty 	      = 50%     
End

;------------------------------------------------------------------------------
Armor SoldierEliteArmor
  Armor = DEFAULT             	80% 	;  40% 	
  Armor = SLASH               	80% 	;  40%  
  Armor = PIERCE                60% 	;  20%				RotWK originally 80%
  Armor = SPECIALIST          	30% 	;	
  Armor = CAVALRY	       165% 	;	originally 125%
  Armor = CRUSH              	50% 	;  50%
  Armor = SIEGE               	50% 	; 100%
  Armor = FLAME               	50% 	;   0%
  Armor = FROST          	75%   ;
  Armor = MAGIC               	50% 	; 100%
  Armor = HERO                 100% 	;  50%
  Armor = HERO_RANGED           60% 	;  50%  Originally 100%
  Armor = STRUCTURAL	  	20%	; 	ori
  FlankedPenalty 	      = 50%     
End

;------------------------------------------------------------------------------
Armor SoldierEliteHeavyArmor
  Armor = DEFAULT             	40% 	;  40%
  Armor = SLASH               	40% 	;  40%
  Armor = PIERCE              	30% 	;  20%				RotWK originally 40%
  Armor = SPECIALIST          	15% 	;
  Armor = CAVALRY	       100% 	;	Originally 75%
  Armor = CRUSH              	50% 	;  50%
  Armor = SIEGE               	50% 	; 100%
  Armor = FLAME               	50% 	;   0%
  Armor = FROST          	75%   ;
  Armor = MAGIC               	50% 	; 100%
  Armor = HERO                 100% 	;  50%
  Armor = HERO_RANGED          100% 	;  50%  
  Armor = STRUCTURAL	  	30%	; 	Originally 20% 
  FlankedPenalty 	      = 50%     
End

;------------------------------------------------------------------------------
Armor TowerGuardArmor
  Armor = DEFAULT         	 80%   	; 100%	originally 100%
  Armor = SLASH           	120%   	; 	originally 200%
  Armor = PIERCE          	 75%   	;  50% 	originally 125%		RotWK originally 90%
  Armor = SPECIALIST      	 85%   	;	originally 100%
  Armor = CAVALRY	   	 25%   	;	originally 20%
  Armor = CRUSH            	 10%   	;  50%
  Armor = SIEGE           	100%   	;
  Armor = FLAME           	100%   	;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   	;
  Armor = HERO            	200%   	;
  Armor = HERO_RANGED     	200%   	;
  Armor = STRUCTURAL	  	 55%	;	originally 100%
  FlankedPenalty 	       = 75%         
End

;------------------------------------------------------------------------------
Armor TowerGuardHeavyArmor
  Armor = DEFAULT             	 40%  	;  40%	originally 50%
  Armor = SLASH               	 70% 	; 	originally 150%
  Armor = PIERCE             	 40%  	;  20% 	originally 65%		RotWK originally 50%
  Armor = SPECIALIST         	 30% 	;	originally 50%
  Armor = CRUSH              	  5% 	;  40%
  Armor = CAVALRY	     	 10% 	;	originally 10%
  Armor = SIEGE              	 50% 	; 100%
  Armor = FLAME              	 50% 	;   0%
  Armor = FROST          	 75%   ;
  Armor = MAGIC              	 50% 	; 100%
  Armor = HERO                	100% 	;  50%
  Armor = HERO_RANGED         	100% 	;  50%  
  Armor = STRUCTURAL		 20%	;	
  FlankedPenalty 	       = 75%     
End

;------------------------------------------------------------------------------
Armor ArcherArmor
  Armor = DEFAULT         	 85%   	; originally 100%
  Armor = SLASH           	135%   	; originally 100%
  Armor = PIERCE          	 60%   	; originally 100%
  Armor = SPECIALIST       	135%   	; originally 100%
  Armor = CAVALRY	  	185%   	; originally 200%
  Armor = CRUSH            	200%   	;
  Armor = SIEGE           	100%   	;
  Armor = FLAME           	100%   	;
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   	;
  Armor = HERO            	200%   	;
  Armor = HERO_RANGED     	200%   	; 
  Armor = STRUCTURAL	  	 40%	; originally 20% 
  FlankedPenalty 	       = 50%      
End

;------------------------------------------------------------------------------
Armor ArcherHeavyArmor
  Armor = DEFAULT            	 40% 	; originally 50%	
  Armor = SLASH              	 85% 	; originally 50%
  Armor = PIERCE             	 30% 	; originally 50%
  Armor = SPECIALIST         	 85% 	; originally 100%
  Armor = CAVALRY	      	100% 	; 
  Armor = CRUSH               	100% 	;
  Armor = SIEGE              	 50% 	;
  Armor = FLAME              	 50% 	;
  Armor = FROST          	 75%   ;
  Armor = MAGIC              	 50% 	;
  Armor = HERO                	100% 	;
  Armor = HERO_RANGED         	100% 	;
  Armor = STRUCTURAL	 	 20%	; originally 100%
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------
Armor ArcherEliteArmor
  Armor = DEFAULT          	 80%   	; 100%	originally 100%
  Armor = SLASH           	125%   	; 200% 	originally 100%
  Armor = PIERCE           	 50%   	; 100% 	originally 100%
  Armor = SPECIALIST       	125%   	; 	originally 100%
  Armor = CAVALRY	   	165%	; 	originally 200%
  Armor = CRUSH            	200%   	; 100%
  Armor = SIEGE           	100%   	;
  Armor = FLAME            	100%   	;
  Armor = FROST          	100%   ;
  Armor = MAGIC            	100%   	;
  Armor = HERO             	200%   	;
  Armor = HERO_RANGED      	200%   	;   
  Armor = STRUCTURAL	  	 30%	; 	originally 100%
  FlankedPenalty 	       = 50%      
End

;------------------------------------------------------------------------------
Armor ArcherEliteHeavyArmor
  Armor = DEFAULT          	 40%   	; 100%	originally 100%
  Armor = SLASH           	 80%   	; 200%	originally 75%
  Armor = PIERCE           	 25%   	; 100%	originally 25%
  Armor = SPECIALIST       	 80%   	;	originally 75%
  Armor = CAVALRY	   	100%	; 	originally 125%
  Armor = CRUSH            	100%   	; 100%
  Armor = SIEGE           	100%   	;
  Armor = FLAME            	100%   	;
  Armor = FROST          	100%   ;
  Armor = MAGIC            	100%   	;
  Armor = HERO             	200%   	;
  Armor = HERO_RANGED      	200%   	;   
  Armor = STRUCTURAL	  	 15%	; 	originally 100%
  FlankedPenalty 	       = 50%      
End

;------------------------------------------------------------------------------
Armor RangerArmor			
  Armor = DEFAULT          	 90%   	; 100%	originally 100%
  Armor = SLASH           	135%   	; 200% 	originally 100%
  Armor = PIERCE           	 75%   	; 100% 	originally 100%		RotWK originally 90%
  Armor = SPECIALIST       	135%   	; 	originally 100%
  Armor = CAVALRY	   	180%	; 	originally 200%
  Armor = CRUSH            	200%   	; 100%
  Armor = SIEGE           	100%   	;
  Armor = FLAME            	100%   	;
  Armor = FROST          	100%   ;
  Armor = MAGIC            	100%   	;
  Armor = HERO             	200%   	;
  Armor = HERO_RANGED      	200%   	;   
  Armor = STRUCTURAL	  	 40%	;	originally 100%
  FlankedPenalty 	       = 50%      
End

;------------------------------------------------------------------------------
Armor KnightArmor
  Armor = DEFAULT         	 85%   	; 100%	originally 100%
  Armor = SLASH           	 70%   	; 100%	originally 80%
  Armor = PIERCE          	 45%   	; 100%	origanally 50%		RotWK originally 55%
  Armor = SPECIALIST      	135%   	; 200%	originally 200%
  Armor = CRUSH           	  1%   	; 100%
  Armor = SIEGE           	100%   	; 100%
  Armor = FLAME           	100%   	;  50%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   	; 100%
  Armor = HERO            	200%   	; 100%
  Armor = HERO_RANGED     	200%   	; 100%  
  Armor = CAVALRY	  	100% 	; 	
  Armor = STRUCTURAL	  	 80%	;	originally 100%
  FlankedPenalty 	  	= 50%      
End

;------------------------------------------------------------------------------
Armor KnightShieldArmor
  Armor = DEFAULT           	 80%   	; 100%	originally 50%
  Armor = SLASH              	 65%   	;  80%	originally 40%
  Armor = PIERCE             	 40%   	;  20%	originally 25%
  Armor = SPECIALIST         	125%   	; 200%	Originally 100%
  Armor = CRUSH               	  1%   	;  80%
  Armor = SIEGE             	 50%   	; 100%
  Armor = FLAME              	 50%   	;  20%
  Armor = FROST          	 75%   ;
  Armor = MAGIC             	 50%   	; 100%
  Armor = HERO               	100%   	; 100%
  Armor = HERO_RANGED         	100%   	;  50%
  Armor = CAVALRY	  	 85% 	; 	Originally 50%
  Armor = STRUCTURAL	   	 70%	; 	originally 20%
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------
Armor KnightHeavyArmor
  Armor = DEFAULT		 40%  	; originally 50%
  Armor = SLASH			 30%  	; originally 40%
  Armor = PIERCE		 20%  	; originally 25%
  Armor = SPECIALIST		 95% 	; originally 100%
  Armor = CRUSH			  1%   
  Armor = SIEGE			 50%  
  Armor = FLAME			 50%  
  Armor = FROST          	 75%   ;
  Armor = MAGIC			 50%  
  Armor = HERO			100% 
  Armor = HERO_RANGED       	100% 
  Armor = CAVALRY		 70%	; Originally 50%				
  Armor = STRUCTURAL		 25%	; originally 50%			
  FlankedPenalty 	       = 50%				
End

;------------------------------------------------------------------------------
Armor KnightShieldHeavyArmor
  Armor = DEFAULT         	 35%   	;  40%	originally 75%
  Armor = SLASH           	 25%   	;  40%	originally 25%
  Armor = PIERCE          	 15%   	;  20%	originally 60%
  Armor = SPECIALIST      	 85%   	; 150%	originally 250%
  Armor = CRUSH           	 75%   	;  40%
  Armor = SIEGE           	 75%   	;  50%
  Armor = FLAME           	 60%   	;   0%
  Armor = FROST          	 75%   ;
  Armor = MAGIC           	 75%   	; 100%
  Armor = HERO            	 75%   	;  50%
  Armor = HERO_RANGED     	 60%   	;  50%
  Armor = CAVALRY		 55%	; 	Originally 100%
  Armor = STRUCTURAL	  	 20%	;	originally 35%
  FlankedPenalty 	       = 50%    
End








;------------------------------------------------------------------------------
Armor MenWallArmor            	 	; MOTW generic wall armor 
  Armor = DEFAULT       	 10%    ; this sets the level for all nonspecified damage types
  Armor = SIEGE         	100%    ; siege damage						Originally 200%
  Armor = PIERCE        	  1%    ; archer damage
  Armor = FLAME         	  1%    ;
  Armor = FROST          	 30%   ;
  Armor = STRUCTURAL		 25%	; structural damage - Grond inflicts this kind of damage
  Armor = LOGICAL_FIRE	 	  0%	; Fire
End

;------------------------------------------------------------------------------
Armor GondorCastleWall           	;Nigh-invulnerable and ancient walls and wall structures -JBender
  Armor = DEFAULT         0%     	;this sets the level for all nonspecified damage types
  Armor = SIEGE         100% 	 	; 20%     ;siege damage
  Armor = STRUCTURAL	100%	 	;structural damage - Grond inflicts this kind of damage
End

;------------------------------------------------------------------------------
Armor GondorCastleWallUpgrade    	;Nigh-invulnerable and ancient walls and wall structures -JBender
  Armor = DEFAULT         0%     	;this sets the level for all nonspecified damage types
  Armor = SIEGE         100%     	;siege damage
  Armor = STRUCTURAL	 25%	 	;structural damage - Grond inflicts this kind of damage
  Armor = MAGIC		 25%
End
;------------------------------------------------------------------------------
Armor GondorCastleWallUpgradeAsTower    ;Nigh-invulnerable and ancient walls and wall structures -JBender
  Armor = DEFAULT         0%     	;this sets the level for all nonspecified damage types
  Armor = SIEGE         100%     	;siege damage
  Armor = STRUCTURAL	 25%	 	;structural damage - Grond inflicts this kind of damage
  Armor = MAGIC		 25%
  Armor = FLY_INTO	100%		; so nazgul and eagle can swoop into upgrade only when it is a tower
End