////////////////
// ARMOR.INC //
//////////////
//Mordor//
/////////

;------------------------------------------------------------------------------
Armor MordorOrcArmor
  Armor = DEFAULT         	100%   ; 
  Armor = SLASH           	100%   ; 
  Armor = PIERCE           	 85%   ;  Orignally 150%	RotWK originally 100%
  Armor = SPECIALIST     	 40%   ; 
  Armor = CAVALRY	  	190%   ; originally 150%
  Armor = CRUSH           	140%   ; originally 100%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ; 
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ; 
  Armor = STRUCTURAL	  	 65%   ; originally 100%
  FlankedPenalty 	       = 50%   
End

;------------------------------------------------------------------------------
Armor MordorHeavyArmor
  Armor = DEFAULT         	 50%   ; 
  Armor = SLASH           	 50%   ; 
  Armor = PIERCE           	 40%   ; originally 75%		RotWK originally 50%
  Armor = SPECIALIST     	 25%   ; originally 20%
  Armor = CAVALRY	  	130%   ; originally 75%
  Armor = CRUSH           	 70%   ; originally 100%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ; 
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ; 
  Armor = STRUCTURAL	  	 35%   ; originally 20%
  FlankedPenalty 	       = 50%     
End


;------------------------------------------------------------------------------
Armor MordorArcherArmor			; Newly added for expansion
  Armor = DEFAULT            	110% 	; 
  Armor = SLASH             	170%	; 
  Armor = PIERCE             	 90% 	; 
  Armor = SPECIALIST        	165%	; 
  Armor = CRUSH              	200% 	; RotWK originally 100%
  Armor = SIEGE              	 50% 
  Armor = FLAME              	 50% 
  Armor = FROST          	 50%   ;
  Armor = MAGIC              	 50% 
  Armor = HERO                	200% 
  Armor = HERO_RANGED         	200% 
  Armor = CAVALRY	  	200%	; 
  Armor = STRUCTURAL	 	 50%	; 
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------

Armor MordorArcherHeavyArmor		; Newly added for expansion
  Armor = DEFAULT            	 60% 	; 
  Armor = SLASH             	110%	; 
  Armor = PIERCE             	 60% 	; 
  Armor = SPECIALIST        	120%	; 
  Armor = CRUSH              	100% 
  Armor = SIEGE              	 50% 
  Armor = FLAME              	 50% 
  Armor = FROST          	 50%   ;
  Armor = MAGIC              	 50% 
  Armor = HERO                	100% 
  Armor = HERO_RANGED         	100% 
  Armor = CAVALRY	  	140%	; 
  Armor = STRUCTURAL	 	 25%	; 
  FlankedPenalty 	       = 50%    
End