////////////////
// ARMOR.INC //
//////////////
//Rhun//
///////


;------------------------------------------------------------------------------
Armor RhunArmor
  Armor = DEFAULT         	 85%   ; 100%	originally 100%
  Armor = SLASH           	135%   ; 100%	originally 200%
  Armor = PIERCE           	100%   ;  50%	originally 125%		RotWK originally 115%
  Armor = SPECIALIST      	 85%   ;  50%	originally 50%
  Armor = CRUSH           	 10%   ; 200%
  Armor = CAVALRY	 	 25%   ;	originally 20%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ; 
  Armor = STRUCTURAL    	 60%   ; 	originally 100% 
  FlankedPenalty 	       = 75%    
End

;------------------------------------------------------------------------------
Armor RhunHeavyArmor
  Armor = DEFAULT         	 45%   ; 100% 	originally 100%
  Armor = SLASH           	 85%   ; 100% 	originally 200%
  Armor = PIERCE           	 55%   ;  50% 	originally 125%		RotWK originally 75%
  Armor = SPECIALIST      	 45%   ;  50% 	originally 100%
  Armor = CRUSH           	 10%   ; 200%
  Armor = CAVALRY	 	 15%   ;	Originally 20%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ; 
  Armor = STRUCTURAL    	 20%   ;	
  FlankedPenalty 	       = 75%    
End