/////////////////////
// COMMANDSET.INC //
///////////////////
//Rhun//
///////


CommandSet RhunSpellBookCommandSet
	1 = Command_SpellBookWarChant
	2 = Command_SpellBookPalantirVision
	3 = Command_SpellBookCrebain

	4 = Command_SpellBookIsengardTaint
	5 = Command_SpellBookIndustry
	6 = Command_SpellBookDevastation
	7 = Command_SpellBookWildMenAllies
	
	8 = Command_SpellBookFreezingRain
	9 = Command_SpellBookFueltheFires
	10 = Command_SpellBookWatcherAlly 
	
	11 = Command_SpellBookDragonAlly
	12 = Command_SpellBookDragonStrike
End

CommandSet RhunSpellStoreCommandSet
	1 = Command_PurchaseSpellPalantirVision
	2 = Command_PurchaseSpellWarChant
	3 = Command_PurchaseSpellCrebain

	4 = Command_PurchaseSpellWildMenAllies
	5 = Command_PurchaseSpellIsengardTaint
	6 = Command_PurchaseSpellDevastation
	7 = Command_PurchaseSpellIndustry
	
	8 = Command_PurchaseSpellFueltheFires
	9 = Command_PurchaseSpellFreezingRain
	10 = Command_PurchaseSpellWatcherAlly
	
	11 = Command_PurchaseSpellDragonAlly
	12 = Command_PurchaseSpellDragonStrike
End
