////////////////
// ARMOR.INC //
//////////////
//Moria//
////////


;------------------------------------------------------------------------------
Armor GoblinFighterArmor
  Armor = DEFAULT         	110%   ;  	originally 100%
  Armor = SLASH           	125%   ; 	originally 100%
  Armor = PIERCE           	 90%   ;  	originally 150%	RotWK originally 110%
  Armor = SPECIALIST     	 50%   ; 	originally 40%
  Armor = CAVALRY	  	200%   ;	originally 150%
  Armor = CRUSH           	150%   ; 	originally 100%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ; 
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ; 
  Armor = STRUCTURAL	  	 80%   ;	originally 100%
  FlankedPenalty 	       = 50%     
End

;------------------------------------------------------------------------------
Armor WildFighterScavengedArmor
  Armor = DEFAULT        	 65%   ; 	originally 50%
  Armor = SLASH          	 65%   ; 	originally 50%
  Armor = PIERCE          	 45%   ;  	originally 75%	RotWK originally 65%
  Armor = SPECIALIST     	 35%   ; 	originally 20%
  Armor = CAVALRY	 	150%   ;	originally 75%
  Armor = CRUSH          	 50%   ; 
  Armor = SIEGE          	 50%   ;
  Armor = FLAME          	 50%   ; 
  Armor = FROST          	 50%   ;
  Armor = MAGIC          	 50%   ;
  Armor = HERO            	100%   ;
  Armor = HERO_RANGED     	100%   ; 
  Armor = STRUCTURAL	 	 50%   ; 	originally 20%
  FlankedPenalty 	       = 50%      
End

Armor WildArcherScavengedArmor
  Armor = DEFAULT        	 60%   ; originally 50%
  Armor = SLASH          	110%   ; originally 50%
  Armor = PIERCE          	 60%   ; originally 50% 
  Armor = SPECIALIST     	110%   ; originally 50%
  Armor = CAVALRY	  	140%   ; originally 100%
  Armor = CRUSH           	100%   ; 
  Armor = SIEGE          	 50%   ;
  Armor = FLAME           	 50%   ; 
  Armor = FROST          	 75%   ;
  Armor = MAGIC           	 50%   ;
  Armor = HERO            	100%   ;
  Armor = HERO_RANGED     	100%   ; 
  Armor = STRUCTURAL	 	 25%   ; originally 20%
  FlankedPenalty 	       = 50%              
End


;------------------------------------------------------------------------------
Armor WildMarauderArmor
  Armor = DEFAULT         	 90%   ; 100%	originally 100%
  Armor = SLASH           	140%   ; 	originally 200%
  Armor = PIERCE          	 80%   ;  50%	originally 125%	RotWK originally 100%
  Armor = SPECIALIST      	100%   ;	originally 100%
  Armor = CAVALRY	  	 25%   ;	originally 20%
  Armor = CRUSH           	 60%   ;  50%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ;
  Armor = STRUCTURAL	  	 75%   ;	originally 100%	
  FlankedPenalty 	       = 75%         
End

;------------------------------------------------------------------------------
Armor WildMarauderHeavyArmor
  Armor = DEFAULT            	 50% 	;  40%	originally 50%
  Armor = SLASH               	 90% 	;	originally 100%
  Armor = PIERCE            	 40% 	;  20%	originally 65%	RotWK originally 60%
  Armor = SPECIALIST         	 60% 	;	originally 50%
  Armor = CAVALRY	     	 25% 	;	originally 10%
  Armor = CRUSH             	 30%  	;  40%
  Armor = SIEGE              	 50% 	; 100%
  Armor = FLAME              	 50%  	;   0%
  Armor = FROST          	100%   ;
  Armor = MAGIC              	 50% 	; 100%
  Armor = HERO                	100% 	;  50%
  Armor = HERO_RANGED         	100% 	;  50%  
  Armor = STRUCTURAL	 	 20%	;	originally 20%
  FlankedPenalty 	       = 75%     
End

;------------------------------------------------------------------------------
Armor MarauderSwordArmor
  Armor = DEFAULT         	 90%   ; 100%	originally 100%
  Armor = SLASH           	100%   ; 	originally 200%
  Armor = PIERCE          	 80%   ;  50%	originally 125%	RotWK originally 100%
  Armor = SPECIALIST      	 60%   ;	originally 100%
  Armor = CAVALRY	  	100%   ;	originally 20%
  Armor = CRUSH           	 60%   ;  50%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ;
  Armor = STRUCTURAL	  	 75%   ;	originally 100%	
  FlankedPenalty 	       = 75%         
End

;------------------------------------------------------------------------------
Armor MarauderSwordHeavyArmor
  Armor = DEFAULT            	 50% 	;  40%	originally 50%
  Armor = SLASH               	 50% 	;	originally 100%
  Armor = PIERCE            	 40% 	;  20%	originally 65%		RotWK originally 50%
  Armor = SPECIALIST         	 30% 	;	originally 50%
  Armor = CAVALRY	     	 50% 	;	originally 10%
  Armor = CRUSH             	 30%  	;  40%
  Armor = SIEGE              	 50% 	; 100%
  Armor = FLAME              	 50%  	;   0%
  Armor = FROST          	100%   ;
  Armor = MAGIC              	 50% 	; 100%
  Armor = HERO                	100% 	;  50%
  Armor = HERO_RANGED         	100% 	;  50%  
  Armor = STRUCTURAL	 	 20%	;	originally 20%
  FlankedPenalty 	       = 75%     
End

;------------------------------------------------------------------------------
Armor GoblinArcherArmor
  Armor = DEFAULT         	110%   ; 100%	originally 100%
  Armor = SLASH           	170%   ; 100% 	originally 100%
  Armor = PIERCE          	 90%   ;  50% 	originally 100%
  Armor = SPECIALIST       	165%   ;  50% 	originally 100%
  Armor = CRUSH            	200%   ; 200%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ;
  Armor = CAVALRY	 	200%   ;	originally 200%
  Armor = STRUCTURAL	  	 50%   ;	originally 100%
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------
Armor HillTrollArmor		       ; New Armor Type for Expansion
  Armor = DEFAULT         	 75%   ; 	originally 100%
  Armor = SLASH           	100%   ;  	originally 150%
  Armor = PIERCE          	 80%   ;  	originally 125%		RotWK originally100%
  Armor = SPECIALIST       	 80%   ;	originally 100%   
  Armor = CRUSH            	100%   ; 
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ;  
  Armor = FROST          	 50%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ;
  Armor = CAVALRY	 	 20%   ; 	
  Armor = STRUCTURAL	  	 60%   ;	originally 100%
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------
Armor HillTrollHeavyArmor	       ; New Armor Type for Expansion
  Armor = DEFAULT         	 40%   ; 	originally 50%
  Armor = SLASH           	 50%   ; 	originally 75%
  Armor = PIERCE          	 40%   ;   	originally 65%		RotWK originally 40%
  Armor = SPECIALIST       	 40%   ;   	originally 50%
  Armor = CRUSH            	 50%   ; 
  Armor = SIEGE           	 50%   ;
  Armor = FLAME           	 50%   ;  
  Armor = FROST          	 25%   ;
  Armor = MAGIC           	 50%   ;
  Armor = HERO            	100%   ;
  Armor = HERO_RANGED     	100%   ;
  Armor = CAVALRY	 	 15%   ;	originally 10%
  Armor = STRUCTURAL	  	 20%   ;	
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------
Armor WildSpiderlingArmor
  Armor = DEFAULT         	110%   	; 100%	originally 100%
  Armor = SLASH           	100%   	; 100%	originally 50%
  Armor = PIERCE           	 65%   	; 100%	originally 100%		RotWK originally 75%
  Armor = SPECIALIST      	200%   	; 200%	originally 200%
  Armor = CRUSH          	  1%   	; 100%
  Armor = SIEGE           	100%   	;
  Armor = FLAME           	100%   	;  50%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   	;
  Armor = HERO            	200%   	; 100%
  Armor = HERO_RANGED     	200%   	; 200%
  Armor = CAVALRY	  	150% 	; 	Originally 100%
  Armor = STRUCTURAL	  	110%	;	originally 100%
  FlankedPenalty 	       = 50%     
End


;------------------------------------------------------------------------------
Armor WildSpiderHoleSpiderlingArmor
  Armor = DEFAULT         	100%   ; 100%
  Armor = SLASH           	 50%   ; 100%
  Armor = PIERCE          	 65%   ; 100%		RotWK originally 75%
  Armor = SPECIALIST      	500%   ; 200%
  Armor = CRUSH           	100%   ; 100%
  Armor = SIEGE           	110%   ;
  Armor = FLAME           	100%   ;  50%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	100%   ; 100%
  Armor = HERO_RANGED     	100%   ; 200%
  Armor = STRUCTURAL	  	100%	
  FlankedPenalty 	       = 50%     
End

;------------------------------------------------------------------------------
Armor WildSpiderRiderArmor
  Armor = DEFAULT         	 85%   	; 100%	originally 100%
  Armor = SLASH          	 70%   	; 100%	originally 80%
  Armor = PIERCE          	 40%   	;  50%	originally 50%		RotWK originally 45%
  Armor = SPECIALIST      	135%   	;  50%	originally 200%
  Armor = CRUSH           	  1%   	; 200%
  Armor = CAVALRY	  	100%  	; 	Originally 100%
  Armor = SIEGE           	100%   	;
  Armor = FLAME           	100%   	;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   	;
  Armor = HERO            	200%   	;
  Armor = HERO_RANGED     	200%   	; 
  Armor = STRUCTURAL	  	 80%	;	originally 100%
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------
Armor WildSpiderRiderHeavyArmor
  Armor = DEFAULT            	 45% 	;  40%	originally 50%
  Armor = SLASH              	 35% 	;  40%	originally 50%
  Armor = PIERCE             	 20% 	;  20%	originally 25%		RotWK originally 25%
  Armor = SPECIALIST         	 95% 	;	originally 50%
  Armor = CAVALRY	  	 70% 	; 	Originally 100%
  Armor = CRUSH              	100% 	;  50%
  Armor = SIEGE              	 50% 	; 100%
  Armor = FLAME              	 50% 	;   0%
  Armor = FROST          	 50%   ;
  Armor = MAGIC              	 50% 	; 100%
  Armor = HERO                	100% 	;  50%
  Armor = HERO_RANGED         	100% 	;  50%  
  Armor = STRUCTURAL	  	 20%	; 	originally 100%	 
  FlankedPenalty 	       = 50%     
End

;------------------------------------------------------------------------------
Armor MountainGiantArmor
  Armor = DEFAULT      		 25%    ; for all nonspecified damage types 	originally 25%
  Armor = CRUSH        		  1%    ; horseman damage			
  Armor = SLASH         	100%    ; 1%	 ;soldier damage		originally 100%
  Armor = PIERCE       		 50%    ; archer damage				originally 50%
  Armor = SPECIALIST    	200%   	; 200%					originally 200%
  Armor = FLAME         	300%    ; fire damage
  Armor = FROST          	100%   ;
  Armor = SIEGE         	100%    ; siege damage
  Armor = STRUCTURAL   		 25%    ; Structural damage (Ent rocks)		originally 25%
  Armor = CHOP          	100%    ; axe damage
  Armor = HERO          	200%    ; hero damage
  Armor = HERO_RANGED   	200%    ; Hero bow damage
  Armor = CAVALRY 		 75%	; Horse damage				originally 75%
  Armor = MAGIC         	100%    ; hero damage
End
