///////////////////////////
// EXPERIENCELEVELS.INC //
/////////////////////////
//Rohan//
////////


;--------------- ROHAN HEROES -------------------------	
;----------------------	THEODEN	-------------------------------------
ExperienceLevel	TheodenLevel1
	TargetNames			 = RohanTheoden	RohanTheodenCavalry
	RequiredExperience	 = 1   
	ExperienceAward		 = THEODEN_LVL1_EXP_AWARD 
	Rank				 = 1
	Upgrades			 = Upgrade_TheodenLeadership
	SelectionDecal
		Texture			 = decal_hero_good
		Style			 = SHADOW_ALPHA_DECAL
		OpacityMin		 = 50% 
		OpacityMax		 = 100%
		MinRadius		 = 40 ;16
		MaxRadius		 = 200 ;16
		MaxSelectedUnits = 40 ;1
	End	
End	

ExperienceLevel	TheodenLevel2
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL2_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL2_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	2
	AttributeModifiers					=	HeroLevelUpDamage1
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End	
End	

ExperienceLevel	TheodenLevel3
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL3_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL3_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	3
	AttributeModifiers					=	HeroLevelUpDamage2
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End	
End	

ExperienceLevel	TheodenLevel4
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL4_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL4_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	4
	Upgrades						=	Upgrade_TheodenKingsFavor
	AttributeModifiers					=	HeroLevelUpDamage3
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End
End	

ExperienceLevel	TheodenLevel5
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL5_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL5_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL

	Rank							=	5
	AttributeModifiers					=	HeroLevelUpDamage4
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End	
End	

ExperienceLevel	TheodenLevel6
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL6_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL6_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	6
	Upgrades						=	Upgrade_TheodenGloriousCharge
	AttributeModifiers					=	HeroLevelUpDamage5
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End
End	

ExperienceLevel	TheodenLevel7
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL7_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL7_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	7
	AttributeModifiers					=	HeroLevelUpDamage6
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End
End	

ExperienceLevel	TheodenLevel8
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL8_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL8_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	8
	AttributeModifiers					=	HeroLevelUpDamage7
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End
End	

ExperienceLevel	TheodenLevel9
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL9_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL9_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	9
	AttributeModifiers					=	HeroLevelUpDamage8
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End
End	

ExperienceLevel	TheodenLevel10
	TargetNames						=	RohanTheoden RohanTheodenCavalry
	RequiredExperience					=	THEODEN_LVL10_EXP_NEEDED
	ExperienceAward						=	THEODEN_LVL10_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	10
	AttributeModifiers					=	HeroLevelUpDamage9
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits				=	40 ;1
	End
End	


;----------------------	SAM	-------------------------------------
ExperienceLevel	SamLevel1
	TargetNames						=	RohanSam RohanSam_Summoned
	RequiredExperience				=	1	
	ExperienceAward					=	HOBBIT_LVL1_EXP_AWARD 
	Rank							=	1
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel2
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL2_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL2_EXP_AWARD 
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	2
	AttributeModifiers				=	HobbitLevelUpDamage1
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel3
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL3_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL3_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	3
	AttributeModifiers				=	HobbitLevelUpDamage2
	Upgrades						=	Upgrade_ElvenCloak
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel4
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL4_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL4_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	4
	AttributeModifiers				=	HobbitLevelUpDamage3
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel5
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL5_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL5_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	5
	AttributeModifiers				=	HobbitLevelUpDamage4
	Upgrades						=	Upgrade_ElvenCloak
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel6
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL6_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL6_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	6
	AttributeModifiers				=	HobbitLevelUpDamage5
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel7
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL7_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL7_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	7
	AttributeModifiers				=	HobbitLevelUpDamage6
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel8
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL8_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL8_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	8
	AttributeModifiers				=	HobbitLevelUpDamage7
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel9
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL9_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL9_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	9
	AttributeModifiers				=	HobbitLevelUpDamage8
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	SamLevel10
	TargetNames						=	RohanSam
	RequiredExperience				=	HOBBIT_LVL10_EXP_NEEDED 	
	ExperienceAward					=	HOBBIT_LVL10_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	10
	AttributeModifiers				=	HobbitLevelUpDamage9
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	


;----------------------	FRODO -------------------------------------	
ExperienceLevel	FrodoLevel1
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers RohanFrodo_Summoned
	RequiredExperience				=	1	
	ExperienceAward					=	HOBBIT_LVL1_EXP_AWARD 
	Rank							=	1
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End	
End	

ExperienceLevel	FrodoLevel2
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL2_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL2_EXP_AWARD 
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	2
	AttributeModifiers				=	HobbitLevelUpDamage1
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End	
End	

ExperienceLevel	FrodoLevel3
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL3_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL3_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	3
	AttributeModifiers				=	HobbitLevelUpDamage2
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End
End	

ExperienceLevel	FrodoLevel4
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL4_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL4_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	4
	AttributeModifiers				=	HobbitLevelUpDamage3
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End	
End	

ExperienceLevel	FrodoLevel5
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL5_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL5_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	5
	AttributeModifiers				=	HobbitLevelUpDamage4
	Upgrades						=	Upgrade_ElvenCloak
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End	
End	

ExperienceLevel	FrodoLevel6
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL6_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL6_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	6
	AttributeModifiers				=	HobbitLevelUpDamage5
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End	
End	

ExperienceLevel	FrodoLevel7
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL7_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL7_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	7
	AttributeModifiers				=	HobbitLevelUpDamage6
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End	
End	

ExperienceLevel	FrodoLevel8
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL8_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL8_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	8
	AttributeModifiers				=	HobbitLevelUpDamage7
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End
End	

ExperienceLevel	FrodoLevel9
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL9_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL9_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	9
	AttributeModifiers				=	HobbitLevelUpDamage8
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End	
End	

ExperienceLevel	FrodoLevel10
	TargetNames						=	RohanFrodo RohanSamWithFrodoPowers
	RequiredExperience				=	HOBBIT_LVL10_EXP_NEEDED 
	ExperienceAward					=	HOBBIT_LVL10_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	10
	AttributeModifiers				=	HobbitLevelUpDamage9
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40 ;16
		MaxRadius					=	200 ;16
		MaxSelectedUnits			=	40 ;1
	End	
End	



;----------------------	PIPPIN -------------------------------------
ExperienceLevel	PippinLevel1
	TargetNames						=	RohanPippin RohanPippen_Summoned
	RequiredExperience				=	1	
	ExperienceAward					=	HOBBIT_LVL1_EXP_AWARD 
	Rank							=	1
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel2
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL2_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL2_EXP_AWARD 
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	2
	AttributeModifiers				=	HobbitLevelUpDamage1
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel3
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL3_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL3_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	3
	AttributeModifiers				=	HobbitLevelUpDamage2
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel4
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL4_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL4_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	4
	AttributeModifiers				=	HobbitLevelUpDamage3
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel5
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL5_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL5_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	5
	AttributeModifiers				=	HobbitLevelUpDamage4
	Upgrades						=	Upgrade_ElvenCloak
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel6
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL6_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL6_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	6
	AttributeModifiers				=	HobbitLevelUpDamage5
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel7
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL7_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL7_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	7
	AttributeModifiers				=	HobbitLevelUpDamage6
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel8
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL8_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL8_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	8
	AttributeModifiers				=	HobbitLevelUpDamage7
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel9
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL9_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL9_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	9
	AttributeModifiers				=	HobbitLevelUpDamage8
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	PippinLevel10
	TargetNames						=	RohanPippin
	RequiredExperience				=	HOBBIT_LVL10_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL10_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	10
	AttributeModifiers				=	HobbitLevelUpDamage9
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	


;----------------------	MERRY -------------------------------------	
ExperienceLevel	MerryLevel1
	TargetNames						=	RohanMerry RohanMerry_Summoned
	RequiredExperience				=	1	
	ExperienceAward					=	HOBBIT_LVL1_EXP_AWARD 
	Rank							=	1
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel2
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL2_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL2_EXP_AWARD 
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	2
	AttributeModifiers				=	HobbitLevelUpDamage1
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel3
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL3_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL3_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	3
	AttributeModifiers				=	HobbitLevelUpDamage2
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel4
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL4_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL4_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	4
	AttributeModifiers				=	HobbitLevelUpDamage3
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel5
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL5_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL5_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	5
	AttributeModifiers				=	HobbitLevelUpDamage4
	Upgrades						=	Upgrade_ElvenCloak
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel6
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL6_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL6_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	6
	AttributeModifiers				=	HobbitLevelUpDamage5
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel7
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL7_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL7_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	7
	AttributeModifiers				=	HobbitLevelUpDamage6
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel8
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL8_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL8_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	8
	AttributeModifiers				=	HobbitLevelUpDamage7
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel9
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL9_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL9_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	9
	AttributeModifiers				=	HobbitLevelUpDamage8
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	

ExperienceLevel	MerryLevel10
	TargetNames						=	RohanMerry
	RequiredExperience				=	HOBBIT_LVL10_EXP_NEEDED
	ExperienceAward					=	HOBBIT_LVL10_EXP_AWARD 	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	10
	AttributeModifiers				=	HobbitLevelUpDamage9
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits			=	40
	End	
End	






;----------------------	EOMER -------------------------------------	
ExperienceLevel	EomerLevel1
	TargetNames						=	RohanEomer RohanEomerCavalry
	RequiredExperience					=	1	
	ExperienceAward						=	EOMER_LVL1_EXP_AWARD
	Rank							=	1
	Upgrades						=	Upgrade_EomerHorseLordLeader
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	40
	End	
End	

ExperienceLevel	EomerLevel2
	TargetNames						=	RohanEomer RohanEomerCavalry
	RequiredExperience					=	EOMER_LVL2_EXP_NEEDED 
	ExperienceAward						=	EOMER_LVL2_EXP_AWARD
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	2
	Upgrades						= 	Upgrade_EomerOutlawLeader
	AttributeModifiers					=	HeroLevelUpDamage1 EomerPassiveOutlawLeadership

	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	40
	End	
End	

ExperienceLevel	EomerLevel3
	TargetNames						=	RohanEomer RohanEomerCavalry
	RequiredExperience					=	EOMER_LVL3_EXP_NEEDED 
	ExperienceAward						=	EOMER_LVL3_EXP_AWARD	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	3
	AttributeModifiers					=	HeroLevelUpDamage2
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	40
	End	
End	

ExperienceLevel	EomerLevel4
	TargetNames						=	RohanEomer RohanEomerCavalry
	RequiredExperience					=	EOMER_LVL4_EXP_NEEDED 
	ExperienceAward						=	EOMER_LVL4_EXP_AWARD	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	4
	AttributeModifiers					=	HeroLevelUpDamage3 
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	40
	End	
End	

ExperienceLevel	EomerLevel5
	TargetNames						=	RohanEomer RohanEomerCavalry
	RequiredExperience					=	EOMER_LVL5_EXP_NEEDED 
	ExperienceAward						=	EOMER_LVL5_EXP_AWARD	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	5

	AttributeModifiers					=	HeroLevelUpDamage4
	Upgrades						=	Upgrade_EomerSpear
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	40
	End	
End	

ExperienceLevel	EomerLevel6
	TargetNames						=	RohanEomer RohanEomerCavalry
	RequiredExperience					=	EOMER_LVL6_EXP_NEEDED 
	ExperienceAward						=	EOMER_LVL6_EXP_AWARD	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	6
	AttributeModifiers					=	HeroLevelUpDamage5
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	40
	End	
End	

ExperienceLevel	EomerLevel7
	TargetNames						=	RohanEomer RohanEomerCavalry
	RequiredExperience					=	EOMER_LVL7_EXP_NEEDED 
	ExperienceAward						=	EOMER_LVL7_EXP_AWARD	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	7
	AttributeModifiers					=	HeroLevelUpDamage6
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	40
	End	
End	

ExperienceLevel	EomerLevel8
	TargetNames						=	RohanEomer RohanEomerCavalry
	RequiredExperience					=	EOMER_LVL8_EXP_NEEDED 
	ExperienceAward						=	EOMER_LVL8_EXP_AWARD	
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	Rank							=	8
	AttributeModifiers					= 	HeroLevelUpDamage7
	SelectionDecal
		Texture						= 	decal_hero_good
		Style					 	=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					= 	40
		MaxRadius					= 	200
		MaxSelectedUnits				= 	40
	End	
End	

ExperienceLevel	EomerLevel9
	TargetNames						= RohanEomer RohanEomerCavalry
	RequiredExperience					= EOMER_LVL9_EXP_NEEDED 
	ExperienceAward						= EOMER_LVL9_EXP_AWARD	
	LevelUpFx				 		= FX:GandalfLevelUp1FX
	;LevelUpOCL						= OCL_GandalfLevelUp1OCL
	Rank							= 9
	AttributeModifiers					= HeroLevelUpDamage8
	SelectionDecal
		Texture						= decal_hero_good
		Style					 	= SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					= 40
		MaxRadius					= 200
		MaxSelectedUnits				= 40
	End	
End	

ExperienceLevel	EomerLevel10
	TargetNames						= RohanEomer RohanEomerCavalry
	RequiredExperience					= EOMER_LVL10_EXP_NEEDED 
	ExperienceAward						= EOMER_LVL10_EXP_AWARD	
	LevelUpFx						= FX:GandalfLevelUp1FX
	;LevelUpOCL						= OCL_GandalfLevelUp1OCL
	Rank							= 10
	AttributeModifiers					= HeroLevelUpDamage9 
	SelectionDecal
		Texture						= decal_hero_good
		Style						= SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					= 40
		MaxRadius					= 200
		MaxSelectedUnits 				= 40
	End	
End	

;----------- GAMLING ------------------	
ExperienceLevel	GamlingLevel1
	TargetNames						=	RohanGamling	
	RequiredExperience					=	1	
	ExperienceAward						=	GAMLING_LVL1_EXP_AWARD
	Rank							=	1
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1
	End
END	

ExperienceLevel	GamlingLevel2
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL2_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL2_EXP_AWARD
	AttributeModifiers					=	HeroLevelUpDamage1
	Rank							=	2
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	SelectionDecal
		Texture						=	decal_hero_good	
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1	
	End		
END	

ExperienceLevel	GamlingLevel3
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL3_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL3_EXP_AWARD	
	AttributeModifiers					=	HeroLevelUpDamage2
	Rank							=	3
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1	
	End
END

ExperienceLevel	GamlingLevel4
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL4_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL4_EXP_AWARD	
	AttributeModifiers					=	HeroLevelUpDamage3
	Rank							=	4
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1
	End		
END	

ExperienceLevel	GamlingLevel5
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL5_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL5_EXP_AWARD	
	AttributeModifiers					=	HeroLevelUpDamage4
	Rank							=	5
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1	
	End		
END	

ExperienceLevel	GamlingLevel6
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL6_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL6_EXP_AWARD	
	AttributeModifiers					=	HeroLevelUpDamage5
	Rank							=	6
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1	
	End	
END	

ExperienceLevel	GamlingLevel7
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL7_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL7_EXP_AWARD	
	AttributeModifiers					=	HeroLevelUpDamage6
	Rank							=	7
	Upgrades						=   	Upgrade_FaramirCaptainOfGondor
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
  SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1	
	End	
END	

ExperienceLevel	GamlingLevel8
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL8_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL8_EXP_AWARD	
	AttributeModifiers					=	HeroLevelUpDamage7
	Rank							=	8
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1
	End	
END	

ExperienceLevel	GamlingLevel9
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL9_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL9_EXP_AWARD	
	AttributeModifiers					=	HeroLevelUpDamage8
	Rank							=	9
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1	
	End	
END	

ExperienceLevel	GamlingLevel10
	TargetNames						=	RohanGamling	
	RequiredExperience					=	GAMLING_LVL10_EXP_NEEDED
	ExperienceAward						=	GAMLING_LVL10_EXP_AWARD	
	AttributeModifiers					=	HeroLevelUpDamage9
	Rank							=	10
	LevelUpFx						=	FX:GandalfLevelUp1FX
	;LevelUpOCL						=	OCL_GandalfLevelUp1OCL
	SelectionDecal
		Texture						=	decal_hero_good
		Style						=	SHADOW_ALPHA_DECAL
		OpacityMin					=	50%	
		OpacityMax					=	100%
		MinRadius					=	40
		MaxRadius					=	200
		MaxSelectedUnits				=	1	
	End	
END	

;----------------------	EOWYN -------------------------------------	
ExperienceLevel	EowynLevel1
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	1	
	ExperienceAward				=	EOWYN_LVL1_EXP_AWARD 
	Rank					=	1
	Upgrades				=	Upgrade_EowynSmiteTrigger
	SelectionDecal
		Texture				=	decal_hero_good	
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel2
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL2_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL2_EXP_AWARD 				
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	2
	AttributeModifiers			=	HeroLevelUpDamage1
	SelectionDecal
		Texture				=	decal_hero_good	
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel3
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL3_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL3_EXP_AWARD 	
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	3
	AttributeModifiers			=	HeroLevelUpDamage2
	Upgrades				=	Upgrade_MountEowyn
	SelectionDecal
		Texture				=	decal_hero_good
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel4
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL4_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL4_EXP_AWARD 	
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	4
	AttributeModifiers			=	HeroLevelUpDamage3
	Upgrades				=	Upgrade_EowynDisguiseTrigger
	SelectionDecal
		Texture				=	decal_hero_good
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel5
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL5_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL5_EXP_AWARD 	
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	5
	AttributeModifiers			=	HeroLevelUpDamage4
	Upgrades				=	Upgrade_EowynShieldMaiden
	SelectionDecal
		Texture				=	decal_hero_good
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel6
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL6_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL6_EXP_AWARD 
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	6
	AttributeModifiers			=	HeroLevelUpDamage5
	SelectionDecal
		Texture				=	decal_hero_good
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel7
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL7_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL7_EXP_AWARD 
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	7
	AttributeModifiers			=	HeroLevelUpDamage6
	SelectionDecal
		Texture				=	decal_hero_good
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel8
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL8_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL8_EXP_AWARD 
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	8
	AttributeModifiers			=	HeroLevelUpDamage7
	SelectionDecal
		Texture				=	decal_hero_good
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel9
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL9_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL9_EXP_AWARD 
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	9
	AttributeModifiers			=	HeroLevelUpDamage8
	SelectionDecal
		Texture				=	decal_hero_good
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End	

ExperienceLevel	EowynLevel10
	TargetNames				=	RohanEowyn RohanEowynDisguised
	RequiredExperience			=	EOWYN_LVL10_EXP_NEEDED
	ExperienceAward				=	EOWYN_LVL10_EXP_AWARD 
	LevelUpFx				=	FX:GandalfLevelUp1FX
	;LevelUpOCL				=	OCL_GandalfLevelUp1OCL
	Rank					=	10
	AttributeModifiers			=	HeroLevelUpDamage9
	SelectionDecal
		Texture				=	decal_hero_good
		Style				=	SHADOW_ALPHA_DECAL
		OpacityMin			=	50%	
		OpacityMax			=	100%
		MinRadius			=	40
		MaxRadius			=	200
		MaxSelectedUnits		=	40
	End	
End

;------------ SPECIAL UNITS	---------------	
;------------ OATHBREAKERS ---------------
ExperienceLevel	OathbreakerGenericLevel1
	TargetNames						=	RohanOathbreakerHorde RohanOathbreakerHordeSmall RohanOathbreaker RohanOathbreaker1 RohanOathbreaker2 RohanOathbreaker3
	RequiredExperience					=	1
	ExperienceAward		  				=	5
	Rank							=	1
	SelectionDecal
		Texture						=	decal_G_level1
		Texture2					=	decal_good_CO
		Style						=	SHADOW_MERGE_DECAL
		OpacityMin					=	80%
		OpacityMax					=	100%
		MinRadius					=	120
		MaxRadius					=	200	
		MaxSelectedUnits				=	40
	End	
END	



;;;;;;;;;;;;;;;;;;;;;;;;;;;;; STRUCTURES ;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;-------------------- ROHAN BUILDINGS ---------------------------

;------------- RohanArcheryRange -----------------

ExperienceLevel	RohanArcherRangeLevel1
	TargetNames				= RohanArcherRange
	RequiredExperience			= 1
	ExperienceAward		  		= ROHAN_ARCHERYRANGE_LVL1_EXP_AWARD
	Rank					= 1
	Upgrades				= Upgrade_StructureLevel1
End
	
ExperienceLevel	RohanArcherRangeLevel2
	TargetNames				= RohanArcherRange
	RequiredExperience			= ROHAN_ARCHERYRANGE_LVL2_EXP_NEEDED
	ExperienceAward		  		= ROHAN_ARCHERYRANGE_LVL2_EXP_AWARD
	Rank					= 2
	AttributeModifiers			= RohanArcheryRangeHitPointModLvl2 RohanArcheryRangeBuildSpeedModLvl2
	Upgrades				= Upgrade_StructureLevel2
	LevelUpFx				= FX:RohanArcheryRangeUpgrade
End
	
ExperienceLevel	RohanArcherRangeLevel3
	TargetNames				= RohanArcherRange
	RequiredExperience			= ROHAN_ARCHERYRANGE_LVL3_EXP_NEEDED 
	ExperienceAward		  		= ROHAN_ARCHERYRANGE_LVL3_EXP_AWARD	
	Rank					= 3
	AttributeModifiers			= RohanArcheryRangeHitPointModLvl3 RohanArcheryRangeBuildSpeedModLvl3
	Upgrades				= Upgrade_StructureLevel3
	LevelUpFx				= FX:RohanArcheryRangeUpgrade
End

;------------- RohanArmory -----------------

ExperienceLevel	RohanArmoryLevel1
	TargetNames				= RohanArmory
	RequiredExperience			= 1
	ExperienceAward		  		= ROHAN_ARMORY_LVL1_EXP_AWARD
	Rank					= 1
	Upgrades				= Upgrade_StructureLevel1
End
	
;ExperienceLevel	RohanArmoryLevel2
;	TargetNames				= RohanArmory
;	RequiredExperience			= ROHAN_ARMORY_LVL2_EXP_NEEDED
;	ExperienceAward		  		= ROHAN_ARMORY_LVL2_EXP_AWARD
;	Rank					= 2
;	AttributeModifiers			= RohanArmoryHitPointModLvl2 RohanArmoryBuildSpeedModLvl2
;	Upgrades				= Upgrade_StructureLevel2
;	LevelUpFx				= FX:RohanArmoryUpgrade
;End
	
;ExperienceLevel	RohanArmoryLevel3
;	TargetNames				= RohanArmory
;	RequiredExperience			= ROHAN_ARMORY_LVL3_EXP_NEEDED  
;	ExperienceAward		  		= ROHAN_ARMORY_LVL3_EXP_AWARD 	
;	Rank					= 3
;	AttributeModifiers			= RohanArmoryHitPointModLvl3 RohanArmoryBuildSpeedModLvl3
;	Upgrades				= Upgrade_StructureLevel3
;	LevelUpFx				= FX:RohanArmoryUpgrade
;End

;------------- RohanStables -----------------

ExperienceLevel	RohanStablesLevel1
	TargetNames				= RohanStable
	RequiredExperience			= 1
	ExperienceAward		  		= ROHAN_STABLES_LVL1_EXP_AWARD
	Rank					= 1
	Upgrades				= Upgrade_StructureLevel1
End
	
ExperienceLevel	RohanStablesLevel2
	TargetNames				= RohanStable
	RequiredExperience			= ROHAN_STABLES_LVL2_EXP_NEEDED
	ExperienceAward		  		= ROHAN_STABLES_LVL2_EXP_AWARD
	Rank					= 2
	AttributeModifiers			= RohanStablesHitPointModLvl2 RohanStablesBuildSpeedModLvl2
	Upgrades				= Upgrade_StructureLevel2
	LevelUpFx				= FX:RohanStablesUpgrade
End
	
ExperienceLevel	RohanStablesLevel3
	TargetNames				= RohanStable
	RequiredExperience			= ROHAN_STABLES_LVL3_EXP_NEEDED 
	ExperienceAward		  		= ROHAN_STABLES_LVL3_EXP_AWARD	
	Rank					= 3
	AttributeModifiers			= RohanStablesHitPointModLvl3 RohanStablesBuildSpeedModLvl3
	Upgrades				= Upgrade_StructureLevel3
	LevelUpFx				= FX:RohanStablesUpgrade
End

;------------- RohanFarm -----------------

ExperienceLevel	RohanFarmLevel1
	TargetNames				= RohanFarm RohanFarmMultiplayer
	RequiredExperience			= 1
	ExperienceAward				= ROHAN_FARM_LVL1_EXP_AWARD	
	Rank					= 1
	AttributeModifiers			= BasicLevelUpProduction1
	Upgrades				= Upgrade_StructureLevel1
End
	
ExperienceLevel	RohanFarmLevel2
	TargetNames				= RohanFarm RohanFarmMultiplayer
	RequiredExperience			= ROHAN_FARM_LVL2_EXP_NEEDED
	ExperienceAward				= ROHAN_FARM_LVL2_EXP_AWARD
	Rank					= 2
	AttributeModifiers			= RohanFarmLevel2Production RohanFarmHitPointModLvl2
	Upgrades				= Upgrade_StructureLevel2
	LevelUpFx				= FX:RohanFarmUpgrade
End
	
ExperienceLevel	RohanFarmLevel3
	TargetNames				= RohanFarm RohanFarmMultiplayer
	RequiredExperience			= ROHAN_FARM_LVL3_EXP_NEEDED
	ExperienceAward				= ROHAN_FARM_LVL3_EXP_AWARD
	Rank					= 3
	AttributeModifiers			= RohanFarmLevel3Production RohanFarmHitPointModLvl3
	Upgrades				= Upgrade_StructureLevel3
	LevelUpFx				= FX:RohanFarmUpgrade
End