	Blank
	Style = TITLE
	Text = "Credits~The S.E.E. Mod"
	Blank
	Text = "CREDITS:DevelopmentTitle1"
	Text = "The Battle for Middle-earth(tm) II"
	Text = "The S.E.E. Mod"
	Blank
	Blank
	Blank
	Text = "Supported by the Ridder Clan Inc."
	Blank
	Style = MINORTITLE
	Text = "Mod Leader"
	Style = NORMAL
	Text = "Nazgul"
	Blank
	Blank
	Style = MINORTITLE
	Text = "Programmer"
	Style = NORMAL
	Text = "Ridder Geel"
	Blank
	Style = MINORTITLE
	Text = "Head Coder"
	Style = NORMAL
	Text = "Ridder Blauw"
;	Blank
;	Style = MINORTITLE
;	Text = "Vandas Faction"
;	Style = NORMAL
;	Text = "Ridder Blauw"
;	Text = "Ridder Geel"
;	Blank
;	Style = MINORTITLE
;	Text = "Hithaeglir Faction"
;	Style = NORMAL
;	Text = "Nieksa"
;	Text = "Ridder Geel"
;	Text = "Nethelen Narçu"
;	Text = "CTLN7"
;	Blank
;	Style = MINORTITLE
;	Text = "Beasts Faction"
;	Style = NORMAL
;	Text = "Lurtz101"
;	Text = "Ridder Geel"
;	Blank
;	Style = MINORTITLE
;	Text = "Harad Faction"
;	Style = NORMAL
;	Text = "Ridder Geel"
;	Text = "Lurtz101"
;	Text = "Githiran"
;	Blank
;	Blank
;	Style = TITLE
;	Text = "Mappers"
;	Style = NORMAL
;	Text = "Ridder Geel"
;	Text = "Ridder Blauw"
;	Text = "Brabox"
;	Text = "LinkFan"
;	Text = "Masterbadeend"
;	Text = "JohnWayne"
;	Blank
;	Blank
;	Style = TITLE
;	Text = "Idea's"
;	Style = NORMAL
;	Text = "Everyone from above..."
;	Text = "Rutger"
;	Blank
;	Blank
;	Style = TITLE
;	Text = "Beta Testers"
;	Style = NORMAL
;	Text = "Neutron4Ever"
;	Text = "Florisz"
;	Blank
;	Blank
;	Style = TITLE
;	Text = "Extra Thanks to..."
;	Style = NORMAL
;	Text = "robnkarla - For supplying us with the Living World Map!"
//Blanks so that the BFME 2 credits does not come exactly after it :D
	Blank
	Blank
	Blank
	Blank
	Blank
	Blank
	Blank
	Blank
	Blank
	Blank