////////////////
// VOICE.INC //
//////////////////////////
//Missions// Tutorials //
////////////////////////

;------------- BFME2 Training Basic Tutorial ------------------

AudioEvent MTrBas_TrainingOfficer001
  Sounds = MTrBas_OffT001
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer002
  Sounds = MTrBas_OffT002
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer003
  Sounds = MTrBas_OffT003
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer004
  Sounds = MTrBas_OffT004
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer005
  Sounds = MTrBas_OffT005
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer006
  Sounds = MTrBas_OffT006
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer007
  Sounds = MTrBas_OffT007
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer008
  Sounds = MTrBas_OffT008
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer009
  Sounds = MTrBas_OffT009
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer010
  Sounds = MTrBas_OffT010
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer011
  Sounds = MTrBas_OffT011
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer012
  Sounds = MTrBas_OffT012
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer013
  Sounds = MTrBas_OffT013
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer014
  Sounds = MTrBas_OffT014
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer015
  Sounds = MTrBas_OffT015
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer016
  Sounds = MTrBas_OffT016
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer017
  Sounds = MTrBas_OffT017
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer018
  Sounds = MTrBas_OffT018
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer019
  Sounds = MTrBas_OffT019
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer020
  Sounds = MTrBas_OffT020
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer021
  Sounds = MTrBas_OffT021
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer022
  Sounds = MTrBas_OffT022
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer023
  Sounds = MTrBas_OffT023
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer024
  Sounds = MTrBas_OffT024
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer025
  Sounds = MTrBas_OffT025
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer026
  Sounds = MTrBas_OffT026
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer027
  Sounds = MTrBas_OffT027
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer028
  Sounds = MTrBas_OffT028
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer029
  Sounds = MTrBas_OffT029
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer030
  Sounds = MTrBas_OffT030
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer031
  Sounds = MTrBas_OffT031
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer032
  Sounds = MTrBas_OffT032
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer033
  Sounds = MTrBas_OffT033
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer034
  Sounds = MTrBas_OffT034
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer035
  Sounds = MTrBas_OffT035
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70

  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer036
  Sounds = MTrBas_OffT036
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer037
  Sounds = MTrBas_OffT037
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer038
  Sounds = MTrBas_OffT038
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer039
  Sounds = MTrBas_OffT039
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer040
  Sounds = MTrBas_OffT040
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer041
  Sounds = MTrBas_OffT041
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer042
  Sounds = MTrBas_OffT042
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer043
  Sounds = MTrBas_OffT043
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer044
  Sounds = MTrBas_OffT044
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer045
  Sounds = MTrBas_OffT045
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer046
  Sounds = MTrBas_OffT046
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer047
  Sounds = MTrBas_OffT047
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer048
  Sounds = MTrBas_OffT048
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer049
  Sounds = MTrBas_OffT049
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer050
  Sounds = MTrBas_OffT050
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer051
  Sounds = MTrBas_OffT051
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer052
  Sounds = MTrBas_OffT052
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer053
  Sounds = MTrBas_OffT053
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer054
  Sounds = MTrBas_OffT054
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer055
  Sounds = MTrBas_OffT055
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer056
  Sounds = MTrBas_OffT056
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer057
  Sounds = MTrBas_OffT057
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer058
  Sounds = MTrBas_OffT058
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer059
  Sounds = MTrBas_OffT059
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer060
  Sounds = MTrBas_OffT060
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer061
  Sounds = MTrBas_OffT061
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer062
  Sounds = MTrBas_OffT062
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer063
  Sounds = MTrBas_OffT063
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer064
  Sounds = MTrBas_OffT064
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer065
  Sounds = MTrBas_OffT065
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer066
  Sounds = MTrBas_OffT066
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer067
  Sounds = MTrBas_OffT067
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer068
  Sounds = MTrBas_OffT068
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer069
  Sounds = MTrBas_OffT069
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer070
  Sounds = MTrBas_OffT070
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer071
  Sounds = MTrBas_OffT071
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer072
  Sounds = MTrBas_OffT072
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer073
  Sounds = MTrBas_OffT073
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer074
  Sounds = MTrBas_OffT074
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer075
  Sounds = MTrBas_OffT075
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer076
  Sounds = MTrBas_OffT076
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer077
  Sounds = MTrBas_OffT077
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer078
  Sounds = MTrBas_OffT078
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer079
  Sounds = MTrBas_OffT079
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer080
  Sounds = MTrBas_OffT080
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer081
  Sounds = MTrBas_OffT081
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer082
  Sounds = MTrBas_OffT082
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer083
  Sounds = MTrBas_OffT083
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer084
  Sounds = MTrBas_OffT084
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer085
  Sounds = MTRBas_OffT085
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer086
  Sounds = MTRBas_OffT086
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer087
  Sounds = MTRBas_OffT087
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_TrainingOfficer088
  Sounds = MTRBas_OffT088
  Volume = TRAINING_BASIC_MINVOLUME
  MinVolume = TRAINING_BASIC_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_Soldier001
  Sounds = MTrBas_Sold001
  Volume = #ADD( TRAINING_BASIC_MINVOLUME 15 )
  MinVolume = #ADD( TRAINING_BASIC_MINVOLUME 15 )
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_Soldier002
  Sounds = MTrBas_Sold002
  Volume = #ADD( TRAINING_BASIC_MINVOLUME 15 )
  MinVolume = #ADD( TRAINING_BASIC_MINVOLUME 15 )
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_Soldier003
  Sounds = MTrBas_Sold003
  Volume = #ADD( TRAINING_BASIC_MINVOLUME 15 )
  MinVolume = #ADD( TRAINING_BASIC_MINVOLUME 15 )
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70

  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrBas_Soldier004
  Sounds = MTrBas_Sold004
  Volume = #ADD( TRAINING_BASIC_MINVOLUME 15 )
  MinVolume = #ADD( TRAINING_BASIC_MINVOLUME 15 )
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End


;------------------------------------------ Skirmish ---------------------------------------------

AudioEvent MSkirmi_GondorOfficer001
  Sounds = MSkirmi_GonO001
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_GondorOfficer002
  Sounds = MSkirmi_GonO002
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_GondorOfficer003
  Sounds = MSkirmi_GonO003
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_GondorOfficer004
  Sounds = MSkirmi_GonO004
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer001
  Sounds = MSkirmi_IseO001
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer002
  Sounds = MSkirmi_IseO002
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer003
  Sounds = MSkirmi_IseO003
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer004
  Sounds = MSkirmi_IseO004
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer005
  Sounds = MSkirmi_IseO005
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer006
  Sounds = MSkirmi_IseO006
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer007
  Sounds = MSkirmi_IseO007
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer008
  Sounds = MSkirmi_IseO008
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer009
  Sounds = MSkirmi_IseO009
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End

AudioEvent MSkirmi_IsengardOfficer010
  Sounds = MSkirmi_IseO010
  Volume = 85
  MinRange = 400
  MaxRange = 1000
  Type = world everyone voice
  SubmixSlider = voice 
  Limit = 1
End




;------------- BFME2 Training Advanced Tutorial ------------------

AudioEvent MTrAdv_TrainingOfficer001
  Sounds = MTrAdv_OffT001
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer002
  Sounds = MTrAdv_OffT002
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer003
  Sounds = MTrAdv_OffT003
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer004
  Sounds = MTrAdv_OffT004
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer005
  Sounds = MTrAdv_OffT005
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer006
  Sounds = MTrAdv_OffT006
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer007
  Sounds = MTrAdv_OffT007
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer008
  Sounds = MTrAdv_OffT008
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer009
  Sounds = MTrAdv_OffT009
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer010
  Sounds = MTrAdv_OffT010
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer011
  Sounds = MTrAdv_OffT011
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer012
  Sounds = MTrAdv_OffT012
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer013
  Sounds = MTrAdv_OffT013
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer014
  Sounds = MTrAdv_OffT014
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer015
  Sounds = MTrAdv_OffT015
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer016
  Sounds = MTrAdv_OffT016
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer017
  Sounds = MTrAdv_OffT017
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer018
  Sounds = MTrAdv_OffT018
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer019
  Sounds = MTrAdv_OffT019
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer020
  Sounds = MTrAdv_OffT020
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer021
  Sounds = MTrAdv_OffT021
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer022
  Sounds = MTrAdv_OffT022
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer023
  Sounds = MTrAdv_OffT023
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer024
  Sounds = MTrAdv_OffT024
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer025
  Sounds = MTrAdv_OffT025
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer026
  Sounds = MTrAdv_OffT026
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer027
  Sounds = MTrAdv_OffT027
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer028
  Sounds = MTrAdv_OffT028
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer029
  Sounds = MTrAdv_OffT029
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer030
  Sounds = MTrAdv_OffT030
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer031
  Sounds = MTrAdv_OffT031
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer032
  Sounds = MTrAdv_OffT032
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer033
  Sounds = MTrAdv_OffT033
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer034
  Sounds = MTrAdv_OffT034
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer035
  Sounds = MTrAdv_OffT035
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer036
  Sounds = MTrAdv_OffT036
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer037
  Sounds = MTrAdv_OffT037
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer038
  Sounds = MTrAdv_OffT038
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer039
  Sounds = MTrAdv_OffT039
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer040
  Sounds = MTrAdv_OffT040
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer041
  Sounds = MTrAdv_OffT041
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer042
  Sounds = MTrAdv_OffT042
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer043
  Sounds = MTrAdv_OffT043
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer044
  Sounds = MTrAdv_OffT044
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer045
  Sounds = MTrAdv_OffT045
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer046
  Sounds = MTrAdv_OffT046
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer047
  Sounds = MTrAdv_OffT047
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer048
  Sounds = MTrAdv_OffT048
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer049
  Sounds = MTrAdv_OffT049
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer050
  Sounds = MTrAdv_OffT050
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer051
  Sounds = MTrAdv_OffT051
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer052
  Sounds = MTrAdv_OffT052
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer053
  Sounds = MTrAdv_OffT053
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer054
  Sounds = MTrAdv_OffT054
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer055
  Sounds = MTrAdv_OffT055
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer056
  Sounds = MTrAdv_OffT056
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer057
  Sounds = MTrAdv_OffT057
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer058
  Sounds = MTrAdv_OffT058
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer059
  Sounds = MTrAdv_OffT059
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer060
  Sounds = MTrAdv_OffT060
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer061
  Sounds = MTrAdv_OffT061
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer062
  Sounds = MTrAdv_OffT062
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer063
  Sounds = MTrAdv_OffT063
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_TrainingOfficer064
  Sounds = MTrAdv_OffT064
  Volume = TRAINING_ADVANCED_MINVOLUME
  MinVolume = TRAINING_ADVANCED_MINVOLUME
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End

AudioEvent MTrAdv_Soldier001
  Sounds = MTrAdv_Sold001
  Volume = #ADD( TRAINING_ADVANCED_MINVOLUME 15 )
  MinVolume = #ADD( TRAINING_ADVANCED_MINVOLUME 15 )
  VolumeSliderMultiplier = Slider:Voice Multiplier:70
  VolumeSliderMultiplier = Slider:SoundFX Multiplier:70
  VolumeSliderMultiplier = Slider:Ambient Multiplier:70
  Limit = 1
  Type = world everyone voice
  SubmixSlider = Voice
End
