////////////////
// ARMOR.INC //
//////////////
//Harad//
////////


;------------------------------------------------------------------------------
Armor HaradrimArmor
  Armor = DEFAULT         	 70%   ; 100%	originally 100%
  Armor = SLASH           	110%   ; 100%	originally 100%
  Armor = PIERCE          	 55%   ;  50%	originally 50%
  Armor = SPECIALIST      	110%   ;  50%	originally 100%
  Armor = CRUSH           	200%   ; 200%
  Armor = CAVALRY	  	150%   ;	originally 200%
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ;  30%
  Armor = FROST          	140%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ; 
  Armor = STRUCTURAL    	 30%   ;	originally 100%
  FlankedPenalty 	       = 50%    
End

;------------------------------------------------------------------------------
Armor HaradrimHeavyArmor		; Newly added for expansion
  Armor = DEFAULT         	 35%   ; 100%	 
  Armor = SLASH           	 65%   ; 100%	
  Armor = PIERCE          	 30%   ;  50%	
  Armor = SPECIALIST      	 50%   ;  50%	
  Armor = CRUSH           	150%   ; 200%
  Armor = CAVALRY	  	 85%   ;	
  Armor = SIEGE           	100%   ;
  Armor = FLAME           	100%   ;  30%
  Armor = FROST          	100%   ;
  Armor = MAGIC           	100%   ;
  Armor = HERO            	200%   ;
  Armor = HERO_RANGED     	200%   ; 
  Armor = STRUCTURAL    	 20%   ;	
  FlankedPenalty 	       = 50%    
End